### ISSUE TITLE
dir scanning fails on windoze

### ISSUE THREAD

**Issue by RuedigerMoeller** [classgraph/classgraph#1]
solution

``` java
    private void scanDir(File dir, int ignorePrefixLen, boolean scanTimestampsOnly) throws IOException {
        String absolutePath = dir.getPath();
        String relativePath = ignorePrefixLen > absolutePath.length() ? "" : absolutePath.substring(ignorePrefixLen);
        relativePath = relativePath.replace(File.separatorChar,'/'); // <=== INSERTED
```

**Comment by lukehutch** [comment]
Hi Ruediger, I have done a bunch of reworking of how paths work in FastClasspathScanner recently, and I would really appreciate it if you could please test the latest version on Windows, since I don't have a Windows machine to test on, and I don't know of any other users using FastClasspathScanner on Windows.

If you're feeling ambitious, it would be great if you could please also test using FastClasspathScanner with Maven (even just "mvn test" on the FastClasspathScanner project itself), since Maven does some interesting things with the classpath, including using Class-Path: URI entries in jar manifest files.

Thank you!

**Comment by RuedigerMoeller** [comment]
Hi luke, the project I used fpscanner for is currenlty inactive. Anyways as its a very useful utility to have in the back.

I'll run the testsuite on windoze np once I find time.

kind regards,
rüdiger
