### ISSUE TITLE
Making ClassInfo a first-class citizen

### ISSUE THREAD

**Issue by andrebrait** [classgraph/classgraph#192]
While right now it's possible to do so, most methods seem geared towards dealing with class names. While that's fine ( I haven't had much difficulty with it yet), ClassInfo is a very cool class for several usages (I'm using it for a plugin-based architecture of sorts). So having an equivalent to the methods which return lists of class names but returning lists of ClassInfo would be kinda cool, I think.

**Comment by lukehutch** [comment]
@andrebrait actually this is a really good suggestion. In the early days, FCS only dealt in strings, such as class names, but it became clear eventually that there needed to be a way to keep info about a class together in one place, and ClassInfo was born. Then eventually I had to add FieldInfo and MethodInfo. I'm now having to create a MethodParameterInfo class too to keep all the info about method parameters (types, names, annotations) together in one place too. 

I'm going to take on a major API revamp at some point, and I think I'm going to go with using ClassInfo as the main way to get results from FCS -- then if you want the class name, you have to call a getter, rather than the other way around (looking up the ClassInfo for a class name). I'll return lists of ClassInfo as you suggest (I will probably implement a ClassInfoList that extends `List<ClassInfo>` for this purpose, and then I'll add a method to this List object that will get all class names in the list as a `List<String>`).

It would also then make sense to have MatchProcessors be passed a ClassInfo object too -- and they can get a `Class<?>` ref from the ClassInfo if they need it. That way MatchProcessors can either call the classloader or not, as needed.

I'll link to this bug from the API change bug, to remind myself to restructure the API this way. Thanks for getting me thinking more deeply about this!

**Comment by andrebrait** [comment]
@lukehutch Cool. I was thinking the same way, but then I realized I could just use the map and so I settled for that. It's not that big of a problem but I think using ClassInfo would be the way to go.

I have another suggestion that'll post to the API Cleanup (it's about the way AnnotationInfo stores things). Or should I create another report so you can link them and close? Which do you prefer?

**Comment by andrebrait** [comment]
Do you think having ```ClassInfo#getSubclasses()``` is feasible? Since you mentioned having the equivalent for getting the ClassInfo of a super class.

**Comment by lukehutch** [comment]
Please create a separate bug for each request, and I'll link them, to try to keep that other bug from getting even more complicated...

Yes, I'll add methods for getting any related class (subclasses, annotations, etc.)

**Comment by lukehutch** [comment]
@andrebrait You were absolutely right in suggesting this, `ClassInfo` is the right path forward, along with the other corresponding classes that have gradually sprung up as FCS has become more mature: `MethodInfo`, `MethodParameterInfo`, `FieldInfo`, and `AnnotationInfo`. I actually just completed an enormous API cleanup and refactoring marathon, and threw out all of the API that doesn't deal with `ClassInfo` and related objects directly. Now all of FCS is based on these wrapper objects, and it's a heck of a lot cleaner and nicer to use. This will be released in version 4 in the next couple of days.

Thanks for the suggestion!

**Comment by andrebrait** [comment]
You're welcome, @lukehutch
I'm watching and I'll look forward to testing v4 when ypu consider it good enough for that :)
