### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by basaam2018** [classgraph/classgraph#235]
Update AssertJ to version 3.10.0

**Comment by johnou** [comment]
Pull requests are welcome.

**Comment by lukehutch** [comment]
Just curious -- maybe it should be upgraded, but what is the issue with depending upon an old version of AssertJ? It only affects the running of unit tests, and it is a test-only dependency, so the actual deployed jarfile shouldn't even have a dependency upon AssertJ.

Just asking in case the test-only deps are being accidentally required by the built jars or something.

**Comment by lukehutch** [comment]
Actually @basaam2018 did you check the git master version? AssertJ is already at 3.10.0. You must be using an old version of ClassGraph.

There were two or three of the initial releases where some of the files in the root directory of the project (including `pom.xml`) accidentally got reverted to old versions, and this downgraded the versions of the dependencies too.

I'll close this since AssertJ is already updated. But I'm still curious to hear how a test-only dependency on an old version was affecting you, in case the deploy deps weren't set up correctly or something. Please comment here, even though the bug is closed.
