### ISSUE TITLE
Please allow basic wildcards to be used in blacklisting jars

### ISSUE THREAD

**Issue by GedMarc** [classgraph/classgraph#242]
In a spot where I would like to blacklist jar files, maven by default assigns versions numbers to jars and these should be searchable without specifying any version.

The list of known JARS to be scanned is unknown. The list of jars to be excluded may become pretty large.

The only JAR to scan in the verbose file is module "com.jwebmp.examples.demos.homepage", again this is unknown at the time of compiling the library.

Currently the config is : 
IPathScanningContentsScanner Final Configuration - [META-INF]
IPathContentsBlacklistScanner Final Configuration - [META-INF/services, META-INF/resources]
IScanJarExclusions Final Configuration - [animal-sniffer-annotations*,antlr*,aopalliance*,apiguardian-api*,btm*]

The excluded JAR file is scanned 
ClassGraph	---- Scanning module[module antlr, location=file:///C:/AESoft/Maven%20Repository/antlr/antlr/2.7.7/antlr-2.7.7.jar]; ClassLoader jdk.internal.loader.ClassLoaders$AppClassLoader@1f28c152 -> file:///C:/AESoft/Maven%20Repository/antlr/antlr/2.7.7/antlr-2.7.7.jar (took 0,001154 sec)
2018-08-28T00:27:35.417+0200	ClassGraph	---- Scanning module[module aopalliance, location=file:///C:/AESoft/Maven%20Repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar]; 

While this is in JDK10, the project is multi-build from JRE 8 through to JRE11ea. The behaviour is the same though.

[classgraph_jar_exclusionbs.txt](https://github.com/classgraph/classgraph/files/2325860/classgraph_jar_exclusionbs.txt)

Thaaaaaaanks!!!!

**Comment by lukehutch** [comment]
I tested jar whitelisting/blacklisting with `*` wildcards, and it works for me. What specifically were you trying to illustrate in the logs? Can you please produce a smaller testcase showing the problem?

**Comment by GedMarc** [comment]
Sure! :)

2018-08-28T18:52:09.200+0200	ClassGraph	-- jarWhiteBlackList: blacklistGlobs: [commons-text*, commons-lang3*]

Then the violation : 

2018-08-28T18:52:09.294+0200	ClassGraph	---- Scanning module classpath entry C:/AESoft/Maven Repository/org/apache/commons/commons-text/1.4/commons-text-1.4.jar (took 0,017498 sec)
2018-08-28T18:52:09.304+0200	ClassGraph	------ Found whitelisted file: META-INF/LICENSE.txt
2018-08-28T18:52:09.302+0200	ClassGraph	------ Found whitelisted file: META-INF/MANIFEST.MF
2018-08-28T18:52:09.305+0200	ClassGraph	------ Found whitelisted file: META-INF/NOTICE.txt
2018-08-28T18:52:09.306+0200	ClassGraph	------ Found whitelisted file: META-INF/maven/org.apache.commons/commons-text/pom.properties
2018-08-28T18:52:09.306+0200	ClassGraph	------ Found whitelisted file: META-INF/maven/org.apache.commons/commons-text/pom.xml



[persistencefilesproject.zip](https://github.com/classgraph/classgraph/files/2329005/persistencefilesproject.zip)

[tiny_log.txt](https://github.com/classgraph/classgraph/files/2329012/tiny_log.txt)

**Comment by lukehutch** [comment]
@GedMarc That's because you have included commons-text as a module, not as a jarfile! Try `.blacklistModules("org.apache.commons.text")` -- that should do it.

Module names should also support wildcards, so you could try `.blacklistModules("org.apache.*")`.

**Comment by GedMarc** [comment]
You are right it does work as expected in JDK 8,
Oh this is a show stopper, or I drop support for JDK8 and go pure JPMS.

**Comment by GedMarc** [comment]
No worries man, it was a passing thought to quicken the beast.
I'm just going to leave it the way it is, it is a fairly unique requirement

**Comment by lukehutch** [comment]
@GedMarc As far as I understand it, one of the key intents for the module system is to allow different versions of a module to be depended on by different modules in the runtime. It would be very unusual to have two modules of the same name but different versions visible at the same time, since the second module can only exist as a "fallthrough" for the first module (by the JEP, two modules of the same name cannot exist in the same directory in the module path, but can exist in different directories, with the first instance failing over to the second if a package or class is not found).

You can currently get the module version for a *specific* `ClassInfo` object using `ClassInfo#getModuleRef()#getLocation()`, which will return the full jar URL, including version code, assuming that the module is not a system module. (System modules have `jrt:/` URIs that don't include version info or even a file path to the location on disk of the system module, just the module name. But system modules are not scanned by default, so you don't need to blacklist them anyway.)

I will work on exposing more of the `ModuleDescriptor` calls in ClassGraph's reflection-based proxy, `ModuleRef`, e.g. I will expose `ModuleDescriptor#getRawVersion()` as `ModuleRef#getRawVersion`. I also just added `Resource#getModuleRef()`, so you can get the module info for `Resource` objects too.

As far as compatibility between JDK 8 and JDK 10, correct, you need to blacklist both modules *and* jars to make the blacklisting work across both modular and non-modular uses of the thing you want to blacklist.

As far as multi-build systems, I don't have a clue how that works, beyond the info in this comment -- you'll have to try it out and see what happens. But I suspect that in most cases, you will only ever see one version of any module from any location in a multi-build runtime.

**Comment by lukehutch** [comment]
PS in JDK 9+, you can already get the module version using `((ModuleDescriptor) moduleRef.getDescriptor()).getRawVersion()`.

**Comment by lukehutch** [comment]
Published in 4.1.3.

**Comment by GedMarc** [comment]
Ohhh great! 
I'm not sure that's true though, to allow different versions of a module to be depended on. The point is to remove the duplication? Strict packaging, 11 brings with it no filename based modules, and you definitely cannot use any older JARS that do not specify compatibility with JPMS anymore "AUTOMATIC-bla bla bla". You cannot share packages, or modules, and the visibility of a JAR to the JVM no longer designates accessibility from your app. Also, That is correct for JEP, but Keeping two versions of the same JAR/package on the classpath in JPMS crashes the runtime engine with a given error of shared packages, and the JVM doesn't even boot. In JDK 11 the error produced is multiple equal dependencies.
I really don't think any of that is true anymore, at least, not from 10 and up.

The default structure for multibuild is to use meta-inf/versions but the byte code is compiled in a single language so it isn't quite.. "multi build" more... "keep the old people somehow happy". Runtime arguments such as --illegal-access which in 9 and 10 are used to enable and keep this "backwards compatibilty" or "duplicate dependencies" no longer exists in 11 and you cannot do it at all anymore.

**Comment by lukehutch** [comment]
It's not true that two modules of the same name crashes the runtime. By design, you can have the same-named module multiple times on the module path, you just can't have two modules of the same name in the same directory on the module path:

https://stackoverflow.com/questions/46573572/java-9-possible-to-have-2-modules-with-same-name-on-module-path

The module system is a DAG of layers. You can also have modules of the same name occur in different layers.

What this means is that you could construct a system where (like with npm) each dependency you pull in can depend on its own version of a library. But you will only see the specific modules that are exported to you. This is the key point. Each part of the module system gets to see only their own layer and parent/ancestral layers. So that's why you probably don't have to filter modules by version in your code, but rather by name: the version is explicitly set up in the module path. That's where you mess with version numbers if you need to change them.

**Comment by GedMarc** [comment]
No longer true in JDK 10. Ill build you a POC.

**Comment by lukehutch** [comment]
Can you point to a change to the JPMS spec where this occurred? I should know the details, since this will come up again, I'm sure.
