### ISSUE TITLE
works fine on Kotlin

### ISSUE THREAD

**Issue by davidmoshal** [classgraph/classgraph#243]
Comment: works well on Kotlin

**Comment by lukehutch** [comment]
Thanks for verifying. I know at least one other user is using ClassGraph on Kotlin, because the Kotlin compiler is a bit sketchy in how it generates method signatures, and this led to a long series of bugfixes and workarounds. There are no other known issues on Kotlin right now, but please report any you find. Thanks.

**Comment by davidmoshal** [comment]
Seems to pick up eg inner classes: 

e.g (apologies for the kotlin code):
```kotlin

package app

import io.github.classgraph.ClassGraph

open class Super

class Outer {

    class Inner : Super() { // ie: extends super
        var a: String = ""
    }

}

fun main(args: Array<String>) {

    val result = ClassGraph()
            .enableAllInfo()
            .whitelistPackages("gui")
            .scan().apply {
                getSubclasses(Super::class.java.name)
                        .forEach {
                            println(it)
                        }

            }
}


```
prints: `public final synchronized class app.Outer$Inner`

BTW - the new classinfo filter feature is great, this project has improved dramatically, kudos!

one issue, not sure how to solve this, but the project name change means that gradle dependency checker has the latest version as an old version 4 release candidate !
(though nice name)

**Comment by lukehutch** [comment]
Yes, inner classes and anonymous inner classes are supported -- you can even call `ClassInfo#getInnerClasses()` and `ClassInfo#getOuterClasses()` to look at the containment hierarchy. This is not Kotlin-specific -- Kotlin just uses Java's conventions there.

As far as the dependency -- it sounds like you are still depending upon the `fast-classpath-scanner` dep, since the name change was made after the switch to 4.x release candidate versioning. You need to update the dep to `classgraph`. Maven equivalent here, you can convert that to Gradle:

https://github.com/classgraph/classgraph/wiki/Porting-FastClasspathScanner-code-to-ClassGraph

**Comment by davidmoshal** [comment]
re the dependency, my point is just that unless I looked at your site and discovered the re-name, then the dependency update library (com.github.ben-manes.versions) would have been quite happy with the old library. 
Not sure there is anything you can do about that though.

**Comment by lukehutch** [comment]
I published a Maven redirect at the last 4.x RC version, so most tools should actually have given the user a message or warning about the rename. I'm sure there are some tools or environments that don't though. Thanks for the heads-up though. I think it will take a while for projects to all switch over. Not many projects are good about keeping an eye on updates of their dependencies.
