### ISSUE TITLE
JEP-181 Preparation

### ISSUE THREAD

**Issue by andrebrait** [classgraph/classgraph#251]
I know there are tests for JDK 11 already, but I wanted to make sure this is on your radar:

http://openjdk.java.net/jeps/181

**Comment by lukehutch** [comment]
Thanks, I knew bridge methods and synthetic accessors were going away, but I hadn't considered what that might mean for ClassGraph.

Since ClassGraph reads the classfile binary format directly, it can already see anything in the class (violating encapsulation) as long as the package the classfile is in is exported to the class running the scan, hence the `ignoreMethodVisibility()` etc. methods.

Looking at the JEP, it looks like this coming change affects inter-class visibility, so the only way this would affect ClassGraph is if ClassGraph wants to respect the "within-nest" visibility, i.e. treating private methods and fields within a class as visible if the scanned class is "nestmates" (who comes up with these terms?) with *the class that the scanner is running within*. I don't see any actual API for finding the `NestHost` and/or `NestMembers` programmatically, so this would mean that the class performing the scan would have to be scanned too, in order to read these attributes from its classfile as well as from the classfiles of the scanned classes. 

How useful would it be, really, to implement these semantics? I think returning only public methods/fields unless `.ignoreMethodVisibility()` / `.ignoreFieldVisibility()` (and then returning everything if these are called) is not unreasonable.

The other thing that could be done is that the `NestHost` and `NestMembers` attributes could be extracted from classfiles, and returned to the user via `ClassInfo#getNestHost()` and `ClassInfo#getNestMembers()`. There are already similar methods for getting inner and outer classes. But how many users will care about knowing the nesting, if the nesting only affects inter-class access control?

**Comment by andrebrait** [comment]
Oh, yeah, no idea.

I just wanted to put this on your radar in case it could affect ClassGraph somehow.

If it doesn't, we can close this :)

**Comment by lukehutch** [comment]
All good :-)  I appreciate the heads-up. I think ClassGraph will continue to function exactly the same as before, even after this change. The main thing that could be done is to implement `ClassInfo#getNestHost()` and `ClassInfo#getNestMembers()` -- but I think that's obscure enough that I'll wait for somebody to specifically request it before implementing it.

Thanks!
