### ISSUE TITLE
Classgraph doesn't allow to resolve subclasses/implementors of a class/interface not included into scan path

### ISSUE THREAD

**Issue by pshirshov** [classgraph/classgraph#261]
Hi,

We have kind of a problem which, I believe, shoudl be addressed on ClassGraph level:

```
package x.y

trait Plugin

package a.b

import x.y.Plugin

trait Other extends Plugin
```

```
package my.app.plugins

import a.b.Other

class MyPlugin extends Other {
}
```

In order to be able to find `MyPlugin` I have to add `a.b` package into scan list. 

I think ClassGraph should handle transitive cases on it's own. At the same time I understand that there may be a serious performance impact. So I'm wondering if it's possible and is the idea viable or not.

**Comment by lukehutch** [comment]
@pshirshov Thanks for the report. Yes, this has been a problem since the beginning of this library, and it's stated as a limitation in the documentation somewhere. Currently ClassGraph can follow only a single step in the "downwards" direction (from superclasses to subclasses, interfaces to implementing classes, or annotations to annotated classes) once you get outside a whitelisted path. The single step is possible because the superclass, interface or annotation is named in the scanned/whitelisted subclass / implementing class / annotated class -- but without scanning named classes outside the whitelisted class (what I call "external classes") you can't tell anything more about class relatedness. The alternative is to scan everything in all packages, which is prohibitively expensive.

The Reflections library does extend "upwards" past whitelisted package boundaries by default, to avoid these sorts of unexpected breakages, and I have been wanting to fix this for a long time in ClassGraph.

You are right that fixing this would incur a performance penalty -- primarily because there was no easy way previously (due to the complex parallelized scanning logic in ClassGraph) to scan just a few additional classes to extend the class hierarchy past the whitelisted package boundary. However, I made a change a couple of months ago that makes fixing this issue much easier now, so it is worth doing it. I'll start working on the change.

**Comment by lukehutch** [comment]
@pshirshov I checked a fix into master. It's a big change, so can you please try building and testing the master revision (`mvn package`) to see if it solves the problem for your usecase?

**Comment by lukehutch** [comment]
I'm pretty sure that this is fixed, so I released this in 4.4.3, and I will close this bug report, but if it's not working for you, please comment here, and I'll reopen it.

**Comment by kaishh** [comment]
It works great, thanks!

**Comment by lukehutch** [comment]
@kaishh Great, thanks for confirming!

**Comment by lukehutch** [comment]
Re. the performance impact, for completeness / for reference:

The performance impact of this change should be minimal. A few extra superclasses, interfaces and annotation classes may be scanned, and ClassGraph has to recursively enumerate directory entries of all directory classpath elements (whereas before, only whitelisted directories were recursively enumerated), so there is more disk I/O for directory classpath elements. However, this enumeration doesn't require the files to actually be read unless they are a superclass, interface or annotation of a whitelisted class (ClassGraph simply needs to scan to see which classes are defined where).

There is no exta performance impact in the enumeration stage for jarfile classpath elements or modules in the module path (though there is the same additional classfile reading and parsing overhead if a whitelist-external superclass, interface or annotation needs to be scanned).
