### ISSUE TITLE
Wiki does not mention whitelistJars supports glob wildcards

### ISSUE THREAD

**Issue by daniel-beck** [classgraph/classgraph#264]
https://github.com/classgraph/classgraph/wiki/API:-ClassGraph-Constructor

`whitelistPaths` and `whitelistPackages` mention that globs are supported, but `whitelistJars` does not.

From https://github.com/classgraph/classgraph/blob/199dcf5388d1830f80024af5bdd8f17fc08a9255/src/main/java/io/github/classgraph/ScanSpec.java#L83 &rarr; https://github.com/classgraph/classgraph/blob/199dcf5388d1830f80024af5bdd8f17fc08a9255/src/main/java/io/github/classgraph/utils/WhiteBlackList.java#L227 &rarr; https://github.com/classgraph/classgraph/blob/199dcf5388d1830f80024af5bdd8f17fc08a9255/src/main/java/io/github/classgraph/utils/WhiteBlackList.java#L152 it looks like this is legal (and useful, to allow for `libname-*.jar`).

Not sure whether the current behavior, which I believe is undocumented support for wildcards, is intentional (I hope it is!), so filing an issue rather than just editing the wiki.

**Comment by lukehutch** [comment]
Yes, this was intentional, and was a requested feature by more than one previous user. There are only a few whitelist/blacklist types that do not support wildcards for specific reasons. I forgot to document this, thanks. I'll go through the whitelist/blacklist criteria and update the Javadoc and the online documentation.

Thanks!
