### ISSUE TITLE
Request - Convenience Methods

### ISSUE THREAD

**Issue by GedMarc** [classgraph/classgraph#275]
Can we add some convenience methods to ClassInfo?

a) findAllGetters
b) findAllGettersWithIs (boolean isEnabled bla bla bla)
c) findAllSetters
d) findAllSettersAnnotatedWith
e) findAllGettersAnnotatedWith
f) findGetterForField
e) findSetterForField

With the new strict encapsulation of JPMS, reflecting to field is no longer recommended and I find myself in a rather strange position xD

**Comment by lukehutch** [comment]
Hmm.. I'm not so sure about this.. I see your point about JPMS, but I'm trying to avoid API bloat. In particular I'm trying to void cross products of filter criteria blowing up the API multiplicatively, which happened with the FastClasspathScnner API, which is why the ClassGraph API includes both filter functions and set operations (so, in particular, `findAllSettersAnnotatedWith` and `findAllGettersAnnotatedWith` should be implemented with a two-stage filter or an intersection).

There's another problem too, which is that getter and setter names follow a naming and capitalization convention that's not 100% robust (there can be false positive matches against other names).

Also, assuming you're fine with applying simple name-based filtering criteria, you can already achieve what you need with a short amount of filtering code, i.e. `classInfo.getMethodInfo().filter(methodInfo -> methodInfo.getName().startsWith("get"))`. So I don't know if it makes sense to add methods that just wrap these simple lambdas. (There are already a few convenience methods like this, but I don't want to add a large number of them.)

Finally, bean-style data classes are (hopefully) going away with the introduction of records into Java in the near future :)

I'm willing to be convinced otherwise, but right now I'm not sure that this makes too much sense.

**Comment by GedMarc** [comment]
Ahh I See, I was going to add it into a utility class and thought perhaps there would be other usages of it as well, but as you point out, it's merely a lambda (I was under the impression it would be a bit harder) so live runtime searches will have very minimal effect.

And most certainly you are correct, the very concept of the "bean" is being thrown away now, I don't believe it will be around for much longer in favour of domain driven designs.
Object pooling is replaced with CDS, which closes the gap on never needing EE again. (I am so 100% behind oracles decision to kill it, there's nothing it does that isn't JDK'd now)

**Comment by lukehutch** [comment]
Not only that, but:

https://dzone.com/articles/updates-on-records-data-classes-for-java
