### ISSUE TITLE
Support for java - loggers

### ISSUE THREAD

**Issue by gitmotte** [classgraph/classgraph#294]
I'd like to add my own PrintStream/Logger for logging. The LogNode - class does not support that and logs per default to System.err.

The standard - logging system of java is java.util.logging.Logger, there are many bridges for other logging-facades and system, therefore that would be enough flexible and does not add any dependencies.

**Comment by lukehutch** [comment]
The reason for the LogNode class is that ClassGraph is aggressively parallelized, and mixing together log output from different threads can produce a jumbled order of log entries that is very hard to use for debugging. LogNode also arranges the output into a nice hierarchy for understandability.

LogNode does have an "immediate mode" that writes out log lines as they are generated, and you could add an option to this to write to a Java logger rather than to stderr (if you want to submit a PR) -- and/or you could redirect the hierarchical log output generated at the end to a Java logger.

Unfortunately I never managed to get my head around how all the different Java logging frameworks were supposed to work together, so I wouldnt even know how to get started with this. 

I do know though that Java loggers can capture stderr output, so that would give you a quick workaround, without having to write any code.

LogNode is pretty bare-bones right now, so feel free to improve it!

**Comment by gitmotte** [comment]
[scan.log](https://github.com/classgraph/classgraph/files/2715738/scan.log)

**Comment by gitmotte** [comment]
Thanks for merging!

**Comment by lukehutch** [comment]
@gitmotte I noticed that if any of the ClassGraph tests that run before `LogNodeTest` enable verbose logging by calling `.verbose()` before `.scan()`, then when `LogNodeTest` runs, its test fails. Specifically `systemErrMessages` ends up empty:

https://github.com/classgraph/classgraph/blob/master/src/test/java/io/github/classgraph/test/utils/LogNodeTest.java#L31

Do you know how to fix this, to isolate the logging in this test?

**Comment by lukehutch** [comment]
(reopening)

**Comment by lukehutch** [comment]
Many thanks for the fix!
