### ISSUE TITLE
Latest versions >4.6.10 generates broken .dot file

### ISSUE THREAD

**Issue by wilmerkrisp** [classgraph/classgraph#306]
Version of  classgraph library above 4.6.10 (for example 4.6.12) generates broken file
implementation 'io.github.classgraph:classgraph:4.6.10'
I am testing result .dot file in http://www.webgraphviz.com and other tools
My project for class analyzing very simple (3 classes) https://github.com/wilmerkrisp/archidoc-test

**Comment by lukehutch** [comment]
Thanks for reporting, fixed in 4.6.26.

**Comment by lukehutch** [comment]
@wilmerkrisp PS unrelated to this bug, you might find the following a useful alternative:

`ClassGraph#enableInterClassDependencies()`

followed by 

`ScanResult#generateGraphVizDotFileFromClassDependencies()`

which gives only dependencies between the classes (only one arrow type) -- but it is more thorough than `.generateGraphVizDotFile()`, since it also includes dependencies due to local variables and intermediate values in the bytecode.

**Comment by lukehutch** [comment]
@wilmerkrisp I just fixed several other issues with Graphviz .dot file generation, you probably want to upgrade to the latest ClassGraph release (4.8.11).

**Comment by wilmerkrisp** [comment]
done!
