### ISSUE TITLE
NullpointerException with latest release / Hotfix release request

### ISSUE THREAD

**Issue by marcuslinke** [classgraph/classgraph#315]
Due to a bug in latest release v4.6.32 we got a NullPointerException. This issue is already fixed in master via https://github.com/classgraph/classgraph/commit/8b67c32e6940fad15135513b96f8c5f6dcda269a#diff-0d51f74efad19622aa45807ac453d171L384, so may I ask whether we can get a hotfix release please?

**Comment by lukehutch** [comment]
@marcuslinke I'm very close to pushing out 4.8.0 with about a dozen major bugfixes (some for bugs reported, others for potential bugs I found through static analysis). I have been working to eliminate as many warnings as possible with about five different static analyzer tools. I need a day or two more to finish going through the output of each of the static analyzers, and I'd like to get the whole roundup of fixes into a single release. Is it possible for you to use the git master version until then? Just do `git clone` followed my `mvn install`, then update your `pom.xml` to depend upon `4.6.33-SNAPSHOT`.

If you need a release more urgently than that, I'll backport the fix from that change, and push out a release.

**Comment by marcuslinke** [comment]
@lukehutch Thanks for your really fast reply! No hurry, if we can get a release within the next days we will be fine with this. Btw. we currently migrating from https://github.com/ronmamo/reflections due to some issues with wildfly so thanks for your great library!

**Comment by lukehutch** [comment]
@marcuslinke No problem, I try to be extremely responsive, after filing literally thousands of bug reports in the bug trackers of probably over a hundred open source projects over many years, and finding that at least 95% of the time, nothing at all happens as a result. I'm determined to change that in my own small corner of the software world!

Reflections has not really been actively maintained in forever, and some Reflections bugs have sat unfixed for a long time (though Reflections is still growing in popularity at a really fast rate). I'm glad you're getting some good usage out of ClassGraph.

WildFly support should be working fine in ClassGraph, but please continue to report any bugs you find, and please do test the current master version, if you could, since there have been a ton of changes since 4.6.32. Thanks!

**Comment by lukehutch** [comment]
Released in 4.8.0.

https://github.com/classgraph/classgraph/releases/tag/classgraph-4.8.0

Thanks for the bug report!

**Comment by marcuslinke** [comment]
@lukehutch Nice! Thank you very much!
