### ISSUE TITLE
Annotation processor

### ISSUE THREAD

**Issue by seanf** [classgraph/classgraph#328]
The blurb on the home page says _An uber-fast, ultra-lightweight, parallelized Java classpath scanner, module scanner, and annotation processor_ (`moduleInfoSource` in `pom.xml` has something similar), but does ClassGraph actually provide an annotation processor? I can't find any reference to `javax.annotation.processing` in the code.

**Comment by lukehutch** [comment]
I agree the current wording could be confusing or misleading. It is meant to convey the fact that ClassGraph processes annotations, and provides a convenient way for user code to process annotations, as opposed to that it implements (or allows users to implement) `javax.annotation.processing.Processor`.

I was going to allow the user to provide a `Processor` implementation to ClassGraph, just as the Java annotation processing framework allows, but I figured there wasn't much point, since the Java framework is so easy to call. (Would you still find that useful though?)

Should I drop the "annotation processor" wording? I wanted to list something annotation-related, since the vast majority of classpath scanning usecases involve looking for annotations.

**Comment by seanf** [comment]
@lukehutch Every term in computing is an overloaded one... Maybe annotation scanner, indexer or finder would convey the idea?

I'm afraid I don't understand your question about the user providing a `Processor` implementation. I was searching GitHub for example `Processor`s to learn from, and ClassGraph popped up. 

From the description, I thought there might be an index-builder `Processor`, like the one in atteo classindex, hiding somewhere in ClassGraph.

**Comment by lukehutch** [comment]
My comment about the user providing a `Processor` implementation was that I thought maybe ClassGraph should actually be able to work with user-provided `Processor` implementations (or subclasses of `AbstractProcessor`), so that you can use regular annotation processing code with ClassGraph, rather than having to write new code for the ClassGraph API. Mainly that would allow you to use regular annotation processors at runtime, not just at compiletime. But I don't know how useful that would be.

A related proposal I received from somebody was to add the `javax.lang.model` API (#143). But again I don't see too much benefit to duplicating Java APIs for ClassGraph.

It's probably least confusing to simply change the wording of the ClassGraph docs and `pom.xml` though -- done. Thanks!

**Comment by seanf** [comment]
Thanks @lukehutch. Just FYI, the description in `moduleInfoSource` in `pom.xml` still mentions "annotation processor". Maybe you could reference `${project.description}`.

**Comment by lukehutch** [comment]
@seanf good catch, thanks!
