### ISSUE TITLE
module-info.class is included when scanning by package

### ISSUE THREAD

**Issue by shamsasari** [classgraph/classgraph#352]
In a Java 8 project with dependencies that contain module-info.class, when scanning by package whitelisting, those module-info.class files will be included in the result.

I believe the commit that introduced this change is https://github.com/classgraph/classgraph/commit/afc0608581e529a7df80e8ef4589eed581a73061. I assume it's not intentional that the module-info.class be included.

The attached log file is for a scan that was performed on this project https://github.com/corda/corda but with the ClassGraph version set to 4.8.39. (I'm trying to upgrade our project to the latest version).

[classgraph.verbose.scan.txt](https://github.com/classgraph/classgraph/files/3287217/classgraph.verbose.scan.txt)

**Comment by shamsasari** [comment]
The same issue occurs with whitelisting classes. I believe it's the `enableClassInfo` flag that triggers this.

**Comment by lukehutch** [comment]
I cannot replicate this. Yes, `module-info.class` is now scanned during classpath scanning (so that information can be read from the classfile), but there should be no class called `module-info` in the returned `ScanResult`. See the unit test committed above.

I assume you're only seeing `module-info` in the logfile, and not in your actual `ScanResult` as a returned `ClassInfo` object?

**Comment by shamsasari** [comment]
Sorry, I forgot to mention that they appear in the `ScanResult.getAllResources()` list. We need to use this rather than the classes list to make sure we include any resource files located in the scanned packages.

**Comment by lukehutch** [comment]
@shamsasari Ah, yes, that makes sense. Is it a problem having the module descriptor classfiles in the resources list? They are in fact in the jarfile (as are `package-info.class` files, if any). The returned resources are supposed to reflect any resources discovered in whitelisted packages, which they do.

**Comment by shamsasari** [comment]
The module-info files that are returned are those that exist in the project's dependency, which don't contain the package being scanned.

**Comment by lukehutch** [comment]
> The module-info files that are returned are those that exist in the project's dependencies, which don't contain the package being scanned.

Ah, I think I finally see what you mean -- if the root package `""` is not whitelisted, the `module-info.class` file is still present anyway in the results, so you're seeing these files outside of whitelisted packages?

**Comment by lukehutch** [comment]
The master version now no longer includes `module-info.class` in the resource list if the root package is not whitelisted. Please test and let me know if this solves the problem for you.

**Comment by lukehutch** [comment]
I'm pretty sure this is fixed, so I released this as 4.8.40, and I'll close this bug report (but if it is not fixed for you, let me know, and I'll reopen it):

https://github.com/classgraph/classgraph/releases/tag/classgraph-4.8.40

Note that if the root package `""` is whitelisted (either by whitelisting no packages, or by specifically whitelisting the root package using `new ClassInfo().whitelistPackagesNonRecursively("")` ), then `module-info.class` will still be returned by `scanResult.getAllResources()` in version 4.8.40, since `module-info.class` is in a whitelisted package.

**Comment by shamsasari** [comment]
I think that did the trick. Thanks so much!

**Comment by lukehutch** [comment]
Great, thanks for the report!
