### ISSUE TITLE
ClassCastException during scan when classgraph is shaded

### ISSUE THREAD

**Issue by johnou** [classgraph/classgraph#354]
This seems to be related to scanning modules but I don't have any experience with them so I am at a bit of a loss of what the correct solution might entail. In a nutshell there are two orbit modules which shade classgraph to different packages, then when scanning a class cast exception is thrown as seen below.

```
Caused by: java.lang.ClassCastException: class cloud.orbit.runtime.shaded.io.github.classgraph.ModuleRef cannot be cast to class cloud.orbit.core.shaded.io.github.classgraph.ModuleRef (cloud.orbit.runtime.shaded.io.github.classgraph.ModuleRef and cloud.orbit.core.shaded.io.github.classgraph.ModuleRef are in unnamed module of loader 'app')
 at cloud.orbit.core.shaded.io.github.classgraph.Scanner.<init>(Scanner.java:169)
 at cloud.orbit.core.shaded.io.github.classgraph.ClassGraph.scanAsync(ClassGraph.java:1125)
 at cloud.orbit.core.shaded.io.github.classgraph.ClassGraph.scan(ClassGraph.java:1161)
 at cloud.orbit.core.shaded.io.github.classgraph.ClassGraph.scan(ClassGraph.java:1201)
 at cloud.orbit.core.shaded.io.github.classgraph.ClassGraph.scan(ClassGraph.java:1214)
 at cloud.orbit.actors.runtime.ClassPathSearch.<init>(ClassPathSearch.java:123)
```

**Comment by lukehutch** [comment]
@johnou Ugh...

This problem generally occurs because one piece of code, running inside the `runtime` package, passes a 'ModuleRef' to another piece of code, running inside the `core` package, and both of these packages are running in different classloaders, which load the `ModuleRef` class at different times, and do not share a parent classloader that caches `ModuleRef.class` (or, possibly, one or both of the classloaders use "parent last" delegation). The solution in the general case is to ensure that only one of the two pieces of code ever tries to load any `ClassGraph` classes, so that the classes are only ever loaded by one classloader. I don't know if this is possible or feasible in this case.

In this case though, the two `ModuleRef` classes are in the same module (the unnamed module), with the same classloader, they are just shaded with different package names. So it is similar to the case where you have two different classloaders trying to load the same exact class (in the same package), except that in this case, you have code calling the copy of `ClassGraph` that is shaded to `runtime`, and other code calling the copy of `ClassGraph` that is shaded to `core` -- and a `ModuleRef` is being passed from one piece of code to the other.

This is actually a bug in the shading code -- it should warn you about cases where you pass shaded references to other code that shades its own copy of the same library, and/or allow you to resolve this conflict by shading only a single shared copy of the library.

I don't know much about shading, but there is probably a way to specify a list of jars or packages or modules that should not be shaded. That would be the way to fix this in this case.

(It's not a module issue though.)

**Comment by lukehutch** [comment]
Actually the situation is even more bizarre and broken than I assumed -- the line that throws the exception is:

```java
for (final ModuleRef systemModuleRef : systemModuleRefs) { //...
```

So actually, when `cloud.orbit.core.shaded.io.github.classgraph.Scanner` is being shaded, its classfile is rewritten to shade automatic imports of `io.github.classgraph.ModuleRef` as `cloud.orbit.runtime.shaded.io.github.classgraph.ModuleRef`.

In other words, the classfile in the `core` package is rewritten by the shading code to refer to classes in the `runtime` package. As far as I can tell, that means the shader is broken.

**Comment by johnou** [comment]
There shouldn't be any class leakage in Orbit with classgraph classes but the possible bug with shading sounds scary, maven-shade-plugin is quite old, i'll try updating that to see if it helps.. will keep you posted!

**Comment by johnou** [comment]
@lukehutch I have a hunch of what the issue is, I decompiled one of the shaded Scanner classes and found that nonapi.io.github.classgraph.* isn't being shaded, so any static caches or data in that package will leak into other shaded classgraph packages.

**Comment by lukehutch** [comment]
@johnou It really does seem scary, particularly because teh `Scanner` class that throws the exception and the `ModuleRef` class that it is trying to load *are in the same package* (`io.github.classgraph`). There will be no `import` statement in the source for this reason.

Class names are always fully-qualified in the classfile binary format though, so there are no `import` statement equivalents in classfiles, and the erroneous class name must have been rewritten in the classfile itself.

**Comment by lukehutch** [comment]
> @lukehutch I have a hunch of what the issue is, I decompiled one of the shaded Scanner classes and found that nonapi.io.github.classgraph.* isn't being shaded, so any static caches or data in that package will leak into other shaded classgraph packages.

Well what normally would happen in a case like this is that classes in a package like `nonapi.io.github.classgraph` would get loaded by one classloader, and then a class in say `io.github.classgraph` would try loading the same class in a different classloader. Even if you load the exact same class into two classloaders, you can't cast instances of one of the copies of the loaded class to variables defined in the other classloader.

However in this case, that's not what's going on, because the package name for `ModuleRef` has changed through shading it two different ways.

**Comment by johnou** [comment]
I'm pretty confident that's what is going on here because nonapi is mixed with ModuleRef https://github.com/classgraph/classgraph/blob/1076d6adfe5da62e0e13556d46584c3b582c46fd/src/main/java/nonapi/io/github/classgraph/classpath/ModuleFinder.java

**Comment by lukehutch** [comment]
@johnou you're right... `ModuleFinder` is in `nonapi`, and all the `nonapi` classes were shaded to depend upon the other version of `ModuleRef`, which breaks down at this line:

```java
final List<ModuleRef> systemModuleRefs = moduleFinder.getSystemModuleRefs();
```

So the real question is, why did `nonapi` not get shaded?

**Comment by johnou** [comment]
because it wasn't configured to, I have changed that now.. https://github.com/orbit/orbit/pull/400

**Comment by johnou** [comment]
@lukehutch sorry for the smoke, hope you don't mind that I created a small wiki page in an effort to help others who may need to shade ClassGraph.

https://github.com/classgraph/classgraph/wiki/Shading-ClassGraph

**Comment by johnou** [comment]
As always thanks again for the agile response / brain storm.

**Comment by lukehutch** [comment]
Great, thanks for the contribution! I'll link that page from the build instructions.
