### ISSUE TITLE
Search for classes only in the current context classloader

### ISSUE THREAD

**Issue by nvsnvikram** [classgraph/classgraph#360]
We have a container that is creating multiple child class loaders. However, we want to run classgraph to scan for classes only in the container classloader and not include the ones from child class loaders. How can we do this with current apis?

**Comment by lukehutch** [comment]
You can't scan through child (descendant) classloaders of the current classloader, only through parent (ancestral) classloaders. However, to scan the innermost child classloader only, call `ClassGraph#ignoreParentClassLoaders()` before scanning.

Does that work for you?

**Comment by nvsnvikram** [comment]
Thanks for the quick reply. I probably didn't explain myself clearly. Here is what I have:

Parent_Classloader
     Class PA1
     Class PA2
     Child_Classloader
          Class CA1
          Class CA2

I am running classgraph in parent classloader and want to find only PA1 & PA2. But right now it is finding PA1, PA2, CA1 & CA2. Is there a way to disable looking at classes in Child_Classloader?

**Comment by lukehutch** [comment]
Hmm.. This is not expected behavior, but there are a couple of directories that are autodetected to be part of the classpath of they are present, even if they are not present in the classpath, because some classloaders don't make their classpath fully visible. 

Can you please attach your verbose logs (call `.verbose()`), pointing out which paths in the detected classpath you expected to be there, and which you did not?

**Comment by nvsnvikram** [comment]
Sorry, for taking a little longer to respond. We found the problem to be the way we are scanning for classes through classgraph.
We are using jetty container and loaded some classes at the container level. We are trying to scan these classes using JMX from a webapp classloader. It seems when we do use shared memory jmx, the call stack includes the webapp classloader as well and classgraph is scanning the webapp class as well.
We have changed the scanning to be done at load time and this fixed the problem for us. I will be closing the issue for now.

**Comment by lukehutch** [comment]
OK, thanks for reporting back. You could also call `.overrideClassLoaders(targetClassLoader)` before scanning to scan just the ClassLoader you need.

**Comment by nvsnvikram** [comment]
We tried using overrideClassLoaders but that seems to disable module scanning.

**Comment by lukehutch** [comment]
That's correct, because JPMS modules use their own classloader, so if you override it, modules won't be scanned. Was your target classloader a subclass of the JPMS classloader or something? Or did you want a way to scan a target pre-JPMS classloader as well as the visible modules? Maybe the latter should be supported.
