### ISSUE TITLE
Feature Request: File Permissions in Resource

### ISSUE THREAD

**Issue by jamesward** [classgraph/classgraph#364]
I'm extracting the contents of the JARs and need to preserve file permissions (read, write, exec).  The info is available via `ZipArchiveEntry::getUnixMode` but I'd need that info in `Resource`.

Thanks for this great library!

**Comment by lukehutch** [comment]
Glad you're finding it useful, and great suggestion. Let's add entry timestamps too.

The file that needs to be modified is this one:

https://github.com/classgraph/classgraph/blob/master/src/main/java/nonapi/io/github/classgraph/fastzipfilereader/LogicalZipFile.java

There's a lot of info online about the zip file format, and hopefully it's a pretty simple modification to pull out the permission and timestamp bits. Want to give it a shot?

**Comment by jamesward** [comment]
Thanks!  Working on it.

**Comment by lukehutch** [comment]
Great! The idea would be to find where to read these fields in the zipfile format, then in `readCentralDirectory()`, extract these fields, then pass them through as new parameters to the `FastZipEntry` constructor. You can add new `getTimestamp()` and `getUnixPermissions()` or similar methods to `Resource`, then in `ClasspathElementZip`, you will find a `newResource` method that takes a `FastZipEntry` parameter and constructs a `Resource` as an inner class. Just override those new methods, and pull out the appropriate values from the `FastZipEntry`.

**Comment by lukehutch** [comment]
Note though that you'll also need to update `ClasspathElementDir` and `ClasspathElementModule` to implement these same new `Resource` methods. And actually maybe `getUnixPermissions()` is not ideal, since there are a lot of Windows users of the library... is there a generic way to represent permissions in Java, that you may be able to map the file permissions onto? I only see `File::canRead()`, `File::canWrite()`, and `File::canExecute()`...

Similarly, timestamps should probably be converted to the Java `Timestamp` type or similar, I guess? Or maybe it's OK to return a long number of seconds since the Unix epoch?

**Comment by lukehutch** [comment]
For `ClasspathElementModule`, just return Unix permission `0666` or equivalent, since modules are read-only.

**Comment by lukehutch** [comment]
It looks like there are standard ways to represent access permissions in Java:

https://docs.oracle.com/javase/tutorial/essential/io/fileAttr.html#posix
https://docs.oracle.com/javase/tutorial/essential/io/fileAttr.html#dos

I don't know though if the POSIX version also works on Windows, and ClassGraph needs to work on all of Linux, Mac OS X, and Windows.

**Comment by jamesward** [comment]
Thanks! Here is the PR which we can use to iterate on:
https://github.com/classgraph/classgraph/pull/365

**Comment by lukehutch** [comment]
Released as 4.8.44. Many thanks for your great contribution, @jamesward!

**Comment by jamesward** [comment]
Thanks a ton for the quick turnaround!  Upgraded and working great:
https://github.com/webjars/webjars-locator-core/commit/d2ebbefc1fc90a89d8032caaf35a9b6224e1a15d

Really appreciate your fantastic library and your help with making it work for my use case.

**Comment by lukehutch** [comment]
You're welcome, you did all the hard work, which is rare for anyone to do when filing a feature request!

I didn't know about WebJars, but it's a brilliant idea, and I'll probably use it on future projects.

**Comment by jamesward** [comment]
Thanks!  WebJars is a fun hobby that is actually kinda useful.  :)  I'll let you known when I release the new `classgraph`-based version of `webjars-locator-core`.  It is really nice to be able to rip a ton of code out: https://github.com/webjars/webjars-locator-core/compare/master...webjars:classgraph

> 344 additions and 1,277 deletions

:100:

**Comment by lukehutch** [comment]
ClassGraph does do resource locating (and jarfile handling in general) much better than any other library, since it works for a huge range of different classloader types, and since it contains its own highly optimized nested unzip implementation. You're not making use of either yet (since you are defining a custom classloader, and you don't use nested jars, I think?), but by porting to ClassGraph will give you a lot of flexibility for the future.

https://github.com/classgraph/classgraph/wiki/Classpath-Specification-Mechanisms
