### ISSUE TITLE
Kotlin: $WhenMapping cannot be cast to class

### ISSUE THREAD

**Issue by rxcmr** [classgraph/classgraph#394]
In classes where a when statement is used for an enum, ClassGraph will throw an exception as it cannot cast $WhenMappings to the superclass.

Example code:
```kotlin
override fun execute(event: CommandEvent) {
    classGraphWhenMappings(LVALUE)
  }

  private fun classGraphWhenMappings(mode: SQLItemMode) {
    when (mode) {
      LVALUE -> PilotUtils.info("Hello!")
      ALL -> TODO()
      KEY -> TODO()
      GVALUE -> TODO()
      ID -> TODO()
      GID -> TODO()
      KNI -> TODO()
      NULL -> TODO()
      WILDCARD_ALPHA -> TODO()
      WILDCARD_BETA -> TODO()
    }
  }
```

Logfile: [ClassGraph.log](https://github.com/classgraph/classgraph/files/4001875/ClassGraph.log)

**Comment by lukehutch** [comment]
In the constructor to `com.fortuneteller.dclient.Pilot`, you are apparently calling `ClassInfoList#loadClasses(com.jagrosh.jdautilities.command.Command.class, /* ignoreExceptions = */ false)`, and there is a `$WhenMapping` in this list, which is not a `Command`. 

How did the `$WhenMapping` get in the list? Can you please provide a complete working example as a Maven project?

**Comment by rxcmr** [comment]
[example maven project](https://github.com/classgraph/classgraph/files/4002789/whenMappingsExample.zip)

**Comment by lukehutch** [comment]
This is not a ClassGraph bug. Try changing the following line in your source

```
.allClasses
```

to 

```
.getSubclasses(TestClass::class.java.name)
```

You are fetching all classes in the package `com.fortuneteller.whenmappingsexample.scanned`, and you're trying to cast anything found in that package to `TestClass`. However Kotlin compiles an auxiliary class and puts it into the same package. You're trying to cast that to `TestClass` too, which is impossible. The above change resolves the error, because you take only the subset of classes in the package that are subclasses of the class you want to cast to.
