### ISSUE TITLE
Don't suggest users to use `LATEST`

### ISSUE THREAD

**Issue by melix** [classgraph/classgraph#397]
### Rationale

The README suggests to use `LATEST` as a dependency version. This isn't a good advice as it inherently makes builds non-reproducible (version will change over time).

You should instead update the README for each release (minimally), or, if you really want to suggest to use `LATEST`, also tell your users to use [dependency locking](https://docs.gradle.org/current/userguide/dependency_locking.html).

Thanks for your work!

**Comment by lukehutch** [comment]
You're welcome! 

You make a good point, but this is a double-edged sword, because there are hundreds of projects now stuck on old versions of ClassGraph, because they depend upon a fixed version, and they never update their dependencies:

https://mvnrepository.com/artifact/io.github.classgraph/classgraph

There have been many, many bugs fixed throughout this version history, and all these projects are missing out on those bugfixes...

Actually ClassGraph is now close to 100% feature complete and close to 100% stable (knock on wood). I don't anticipate making any significant changes to the API or to functionality from this point forward, and the bug reporting rate has dropped to almost zero. So any further changes should only be incremental bugfixes that are fully backwards compatible at this point, and `LATEST` should not be a bad default.

That said, every time in the past I thought ClassGraph was "done", I was wrong, so who knows :-)

Still, I made the change you suggested to `README.md`, since the general principle of not depending on `LATEST` is sound. Thanks!
