### ISSUE TITLE
NoSuchMethodError ByteBuffer.position running on Java 8 in 4.8.63

### ISSUE THREAD

**Issue by TWiStErRob** [classgraph/classgraph#403]
I'm getting a weird error with latest 4.8.63:
```
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at nonapi.io.github.classgraph.fileslice.reader.RandomAccessFileReader.read(RandomAccessFileReader.java:93)
	at nonapi.io.github.classgraph.fileslice.reader.RandomAccessFileReader.readInt(RandomAccessFileReader.java:158)
	at nonapi.io.github.classgraph.fastzipfilereader.LogicalZipFile.readCentralDirectory(LogicalZipFile.java:450)
	at nonapi.io.github.classgraph.fastzipfilereader.LogicalZipFile.<init>(LogicalZipFile.java:155)
	at nonapi.io.github.classgraph.fastzipfilereader.NestedJarHandler$3.newInstance(NestedJarHandler.java:140)
	at nonapi.io.github.classgraph.fastzipfilereader.NestedJarHandler$3.newInstance(NestedJarHandler.java:135)
	at nonapi.io.github.classgraph.concurrency.SingletonMap.get(SingletonMap.java:189)
	at nonapi.io.github.classgraph.fastzipfilereader.NestedJarHandler$4.newInstance(NestedJarHandler.java:203)
	at nonapi.io.github.classgraph.fastzipfilereader.NestedJarHandler$4.newInstance(NestedJarHandler.java:150)
	at nonapi.io.github.classgraph.concurrency.SingletonMap.get(SingletonMap.java:189)
	at io.github.classgraph.ClasspathElementZip.open(ClasspathElementZip.java:140)
```

it looks like a binary incompatibility with your compile JDK and my runtime. I'm using 1.8.0-121.
my version has 
```java
public abstract class Buffer {
    public final Buffer position(int newPosition) { ... }

// and

public abstract class ByteBuffer extends Buffer
```

In Java 9 they changed it to:
```java
public abstract class Buffer {
    public Buffer position(int newPosition);

// and

public abstract class ByteBuffer extends Buffer {
    @Override
    public Buffer position(int newPosition) { ... }
```

I think you'll need to do
```
-dstBuf.position(dstBufStart);
+((Buffer)dstBuf).position(dstBufStart);
```
in `nonapi.io.github.classgraph.fileslice.reader.RandomAccessFileReader#read(long, java.nio.ByteBuffer, int, int)` to make the library Java 8 compatible again.

**Comment by lukehutch** [comment]
@TWiStErRob You're correct on your diagnosis of the problem and the fix. I have run into (and fixed) this before, which caused me to add the Animal Sniffer plugin to the build. Strangely though this no longer stops the build with an error when this problem is hit, so I didn't notice it, and running ClassGraph 4.8.63 on jdk1.8.0_241-amd64 on Linux did not trigger the runtime error in my testing, so I missed it during testing too (I have no idea why, because JDK 1.8 used to trigger the runtime error!).

Fixed and released in 4.8.64.

**Comment by TWiStErRob** [comment]
Wow that's a lot of occurrences, confirmed working!

I don't think you would need any extra steps if you compile with the SDK of your lowest target Java level, not just -source -target. Where does the release build come from? Because on Travis you have a Java8 setup.

**Comment by lukehutch** [comment]
I build the release jar on my home machine. But even on Travis, the 4.8.63 build succeeded for some reason on JDK 8, including running the unit tests:

https://travis-ci.org/classgraph/classgraph/jobs/651083000

This is very weird, because it should definitely trigger a runtime exception.

The same issue is true on the GitHub Actions CI build -- no runtime exceptions on JDK 8:

https://github.com/classgraph/classgraph/runs/448822493?check_suite_focus=true

Another oddity is that the animal-sniffer plugin doesn't even run during Travis or GitHub Actions builds, but it does run during build on my home machine. (However this particular signature problem (covariant return type change) does not trigger an error, only a warning, so it doesn't stop the build anyway.)

I reported a bug to the Animal Sniffer project to stop the build on a covariant return type change:

https://github.com/mojohaus/animal-sniffer/issues/77

And I reported a bug to M2Eclipse to try to get a new syntax working that should unify the way you declare plugins in Maven and M2Eclipse (currently you have to jump through the "lifecycle-mapping" hoop to make this work, which is probably why the maven-enforcer-plugin is not running on the Travis or GitHub Actions build):

https://bugs.eclipse.org/bugs/show_bug.cgi?id=560205

Anyway, thanks for pointing this out. I'll try to manually watch for the covariant return type warning in future.

**Comment by TWiStErRob** [comment]
>when building on JDK 8, including running the unit tests:
> This is very weird, because it should definitely trigger a runtime exception.

It shouldn't fail on JDK 8 because it links the right `Buffer` method and runs tests with that. The problem is when you build with JDK 9+ then it links to `ByteBuffer` method (non-existent on JDK7-8) due to a newer bootstrap classpath. I thought that warning was just spam, but now I'm starting to understand what it means :) It'll only fail with a back-compiled binary (-target) on an old JDK. If the compiler and runtime JDK is the same, it'll always work.

> a covariant return type change:

The problem is not the covariant return type change, but the receiver of the call. The bytecode in the .class file when you compile on JDK 8 will be `invokevirtual Buffer.position(int) on local variable` and compiled on JDK 9+ will be `invokevirtual ByteBuffer.position(int) on local variable`. In both cases your local varaible is `ByteBuffer (extends Buffer)`, and the compiler resolves the lowest method  (in the class hierarchy) visible due to declared variable type. Compiling with JDK 9+ will result in an non-existent method on JDK 8, and hence `NoSuchMethodError` above.

I think covariant return types are fine, because even if you assign the covariant type to a local variable it'll be compatible with a variable with the type of the super type.
```java
ByteBuffer localVar = ...;
// doesn't matter if it's Buffer or ByteBuffer returned both of them are assignable to this variable
Buffer returned = localVar.position(1);
```

The easiest way to avoid this in the future is to use the topmost type possible based on the used APIs. i.e. `Buffer` in this case, if you don't use any specific `ByteBuffer` methods. It's similar to how I mostly use `Collection<T>` when all I need is `size()` and `forEach { }`.

**Comment by lukehutch** [comment]
> It'll only fail with a back-compiled binary (-target) on an old JDK. If the compiler and runtime JDK is the same, it'll always work.

Ah, a light bulb just switched on in my head too :-)  Thanks for explaining that! It was a puzzling change, and the first time I ran into it, it seemed like one of the dumbest breaking changes that the JDK team has ever made, since it would cause a runtime crash without giving a compiletime warning. But you're right that it's only an issue when "down-compiling" to a lower ABI version. This is presumably why this change was made to JDK 1.7 build 121 to warn when `-source` was used without specifying the exact `rt.jar` to use with `-booclasspath`:

http://hg.openjdk.java.net/jdk7/jdk7/langtools/rev/c44234f680da

e.g.

https://stackoverflow.com/questions/7816423/warning-options-bootstrap-class-path-not-set-in-conjunction-with-source-1-5

> The easiest way to avoid this in the future is to use the topmost type possible based on the used APIs. i.e. `Buffer` in this case, if you don't use any specific `ByteBuffer` methods. It's similar to how I mostly use `Collection<T>` when all I need is `size()` and `forEach { }`.

Right -- years ago I used to always write

```
ArrayList<Integer> ints = new ArrayList<>();
```

Now I always at a minimum move up to `List` at a minimum, if not `Collection`:

```
List<Integer> ints = new ArrayList<>();
```

**Comment by TWiStErRob** [comment]
That `-booclasspath` option is funny, if you have an older JDK lying around to get the `rt.jar` from, might as well just use it to compile :) I really agree with this [comment](https://stackoverflow.com/questions/7816423/warning-options-bootstrap-class-path-not-set-in-conjunction-with-source-1-5#comment38458958_12050087).

I like learning new weird things in tech, thanks for the discussion :)

**Comment by lukehutch** [comment]
Thanks also, I learned a lot!
