### ISSUE TITLE
overrideClassLoaders(AppClassLoader) not no-op with Java 11

### ISSUE THREAD

**Issue by chrisr3** [classgraph/classgraph#412]
This might just be a semantic issue, but it is an obvious change in behaviour vs running on Java 8.

We are executing ClassGraph as follows:
```kotlin
ClassGraph().overrideClassLoaders(classLoader)
    .ignoreParentClassLoaders()
    .enableClassinfo()
    .scan()
```
The `classLoader` is allowed to be `AppClassLoader`, and this isn't a problem on Java 8. However, it does cause problems on Java 11. I have tested ClassGraph 4.8.58, 4.8.65 and 4.8.67, and none of them finds any `nonSystemModuleRefs`, although 4.8.67 does at least find the `systemModuleRefs`. (To be precise, ClassGraph does find lots of "unnamed modules" on the call-stack, but rejects them all because `layer == null`.)

We are working around this by doing the following:
```kotlin
ClassGraph().apply {
    if (classLoader !== ClassLoader.getSystemClassLoader()) {
        overrideClassLoaders(classLoader)
    }
}.ignoreParentClassLoaders()
 .enableClassinfo()
 .scan()
```
This works because it allows `ClasspathFinder` to consult the `java.class.path` system property and so populate the `classpathOrder` field instead. And to be clear, these _are_ the jars we want to be scanning. We have no need to scan the `systemModuleRefs` here.

See #382 and #411.

**Comment by GedMarc** [comment]
hmm - i've got 66 on jre 14,
This is going to be a really strange one, even to type out really, but in java images JMod, JImage, and JPackage unnamed modules are gone, but the other winner here, is the entire filesystem works on jrt:// 

I also noticed when running "modular" (a.k.a not classpath mode JDK 11) the classpath and jars are (obviously) very empty, and "classpath" as it were, nigh non-existent. 

I'm wondering.. why you would ever use classpath on modular jvm's? I mean i get it, i want the new stuff but not the new way, but as you say, unnamed modules are just one thing your going to face, among many many others, but the backwards compatibility to classpath adds a lot of performance degradation - in relation to running your built jre's from JDK 9 and up. you're really not getting any benefit?

**Comment by GedMarc** [comment]
this is just a general question not aimed at anything other than knowledge gathering

**Comment by lukehutch** [comment]
@chrisr3 interesting. I think I made the decision to check if `layer == null` because unnamed modules have some very weird properties. I don't remember the details. Can you please try removing that check to see if it solves your problem? You may need to override a couple of other statements too, e.g. if the layer is null, set the module name to `""` rather than trying to read it from the module layer.

Some of the weird properties of unnamed modules include that classes on the traditional classpath cannot see or call classes on the module path (or maybe it was the other way around, I don't remember). So actually it doesn't make a lot of sense to have classes on both the traditional classpath and the module path.

There's a huge amount of resistance to modularizing legacy code though. So I don't expect to see widespread adoption of modularization anytime in the near future. I think the JDK team really screwed up a lot of things about JPMS, making it way too complicated.

@GedMarc I don't understand your description, can you please give a concrete example?

**Comment by chrisr3** [comment]
> Can you please try removing that check to see if it solves your problem?

Well, I think the code would complain quite quickly if I removed this `null`-check:
```java
package nonapi.io.github.classgraph.classpath

public class ModuleFinder {

private static List<ModuleRef> findModuleRefsFromCallstack(
            final Class<?>[] callStack,
            final ScanSpec scanSpec,
            final LogNode log) {
    ...
    final Object /* ModuleLayer */ layer = ReflectionUtils.invokeMethod(module, "getLayer",
            /* throwException = */ true);
     // getLayer() returns null for unnamed modules -- have to get their classes from java.class.path 
    if (layer != null) {
        layers.add(layer);
    }
    ...
```
This routine is accumulating a set of layers to be passed here:
```java
return findModuleRefs(layers, scanSpec, log);
```

**Comment by chrisr3** [comment]
> I think the JDK team really screwed up a lot of things about JPMS, making it way too complicated.

That may be true, but the problem we're having is that the JDK is seems to be charging forwards without enough testing, and then not back-porting those bug fixes to previous versions. There were some Crypto-related bugs that were preventing us from moving to Java 11, but the attitude seemed to be that they would only be fixed in Java 13 :expressionless:. And don't forget that Java will be nerfing reflection in later versions too. So I can't decide whether everyone is being route-marched away from Java 8 or being abandoned there.

**Comment by GedMarc** [comment]
I don't think so - I love JPMS, it is so smooth gosh!
I find the number one problem is people sticking to "Java-Only" methodologies like it was their ticket to heaven :)
Take a look at guicedee.com - full JPMS enterprise suite.

They went a step further in jdk12 splitting the "modules" from the "path' - so for service loaders e.g. meta-inf/services no longer exists - which of course with annotation processors, is a bit of a... 

If you put down the old toolbox and pick up the new, with a fresh mind. I don't believe anyone would actually willingly go back to classpath java.
FWIW

**Comment by lukehutch** [comment]
@chrisr3 I just checked in a possible fix. Can you please test? I can't figure out how to set up the classpath and module path so that there is an unnamed module. I think that I need a project A that includes a project B on the traditional classpath, but B (not A) has to call ClassGraph?

**Comment by lukehutch** [comment]
@GedMarc can you please figure out if any of the changes you described (e.g. stricter path encapsulation) could affect scanning with ClassGraph?

**Comment by lukehutch** [comment]
Sorry, the previous fix was incomplete. Should be good to go now.

**Comment by chrisr3** [comment]
Thanks, my tests pass with the new changes. I was slightly concerned that
```kotlin
ClasGraph().apply {
    if (classLoader !== ClassLoader.getSystemClassLoader()) {
        overrideClassLoaders(classLoader)
    }
}
```
was adding an extra 20 elements to the `order` than
```kotlin
ClasGraph().overrideClassLoaders(classLoader)
```
does when `classLoader` is `AppClassLoader`, but then I realised that these 20 jars were all Gradle and so their exclusion was a Good Thing :tm:!

I like it! I like it a lot... :+1:

**Comment by lukehutch** [comment]
@chrisr3 Great! Thanks for confirming. Released in 4.8.68. I appreciate the bug report!

**Comment by GedMarc** [comment]
@lukehutch Hey Luke, we pushed .68 into our production environment today on JLink JDK 14 :)

Still perfect! And still one of the only libraries that is keeping up with the pace of the new 6 month releases!

**Comment by lukehutch** [comment]
@GedMarc Great, thanks for reporting back on this.

Actually ClassGraph can keep up with the 6-monthly release cadence precisely because it ignores the classfile version number -- classfiles are almost always backwards compatible across releases, if you parse only the subset of the classfile that you know how to parse. ASM flat out refuses to parse classfiles with a higher version number than the value when it was released, and as a result, everything that depends upon ASM has to be updated every 6 months, then everything that depends upon everything that depends upon ASM, and so on, to the last transitive dependency.

I had a very long conversation on the jdk-dev mailing list about this. I found that the classfile format was not backwards compatible in one place -- the constant pool. If they add new constant pool entry types (tags), then a classfile parser that encounters an unknown tag simply has to stop parsing, because it doesn't know how large the constant pool entry is for an unknown tag type. I proposed a fix (store the constant pool entry size for new entry tags, as a required constant pool meta-entry). I was trying to make the case that classfile parsing libraries should always be able to parse the subset of classfiles that they understand, and they can just ignore all the new exotic stuff that they don't care about (like ClassGraph doesn't care about "nest mates"). However, one of the core JDK developers strongly disagreed with this, and refused to admit there was any value to backwards/forwards compatibility. He claimed that even though the classfile format had not changed fundamentally since like Java 1.0, it *could* change at any time in a breaking way. I tried to point out that transitive dependencies on ASM are causing widespread breakage every 6 months now, but he didn't care -- he got more and more irate about this the more I pushed for backwards compatibility. I was pretty disappointed with how he handled it, and the fact that nobody else in the JDK team even commented on it.

So I decided I'll just keep ignoring the classfile version number, and if things break, like they did with JDK 9 and JDK 11 due to new constant pool tag types, I'll just fix them when that happens. There's no point breaking things for every user of ClassGraph every 6 months.
