### ISSUE TITLE
ClassGraph on Open Liberty doesn't find any classes from the application.

### ISSUE THREAD

**Issue by michael-simons** [classgraph/classgraph#414]
Here's Michael from Neo4j-OGM project.

A customer reached out to us wanting to run OGM on Websphere Liberty respectively Open Liberty https://openliberty.io.

Turns out, that Neo4j-OGM doesn't find any domain classes in that scenario. After a day of pulling my hair, I'm relatively sure that I can boil this down to interactions of ClassGraph and Liberty.

I followed this guide https://openliberty.io/guides/maven-intro.html and added ClassGraph.

Given the following servlet

```
package io.openliberty.guides.hello;

import io.github.classgraph.ClassGraph;
import io.github.classgraph.ScanResult;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet(urlPatterns="/servlet")
public class HelloServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

        int numberOfClassesFound = 0;
        // The servlet itself should be found... But isnt.
        try (ScanResult r = new ClassGraph().verbose(true).enableRealtimeLogging().enableAllInfo().whitelistPackages("io.openliberty.guides.hello").scan()) {
            numberOfClassesFound = r.getAllClasses().size();
        }


        response.getWriter().append("Number of classes " + numberOfClassesFound + "\n");
    }

    protected void doPost(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException {
        doGet(request, response);
    }
}
```

Should find at least 1 class, the servlet itself.
However, it does not.

Follow this step to recreate from the attached producer

```
unzip classgraph-on-liberty.zip -d reproducer
cd reproducer
mvn liberty:dev   
```

Hit any key after the thing starts or go to http://localhost:9080/ServletSample/servlet

You'll see 0 classes found respectively a failing test.

I have attached the ClassGraph verbose log as well. What sticks out is:

```

[09.04.20 18:12:34:743 MESZ] 0000003d io.github.classgraph.ClassGraph                              I 2020-04-09T18:12:34.743+0200	ClassGraph	Classloader com.ibm.ws.classloading.internal.ThreadContextClassLoader@47126ba2 is handled by nonapi.io.github.classgraph.classloaderhandler.WebsphereLibertyClassLoaderHandler

[09.04.20 18:12:34:745 MESZ] 0000003d io.github.classgraph.ClassGraph                              I 2020-04-09T18:12:34.744+0200	ClassGraph	Found classpath element: /WEB-INF/classes

[09.04.20 18:12:34:745 MESZ] 0000003d io.github.classgraph.ClassGraph                              I 2020-04-09T18:12:34.745+0200	ClassGraph	Found classpath element: /Users/msimons/.m2/repository/io/github/classgraph/classgraph/4.8.68/classgraph-4.8.68.jar

[09.04.20 18:12:34:746 MESZ] 0000003d io.github.classgraph.ClassGraph                              I 2020-04-09T18:12:34.745+0200	ClassGraph	Classloader com.ibm.ws.classloading.internal.GatewayClassLoader@5ec53685 is handled by nonapi.io.github.classgraph.classloaderhandler.FallbackClassLoaderHandler

[09.04.20 18:12:34:749 MESZ] 0000003d io.github.classgraph.ClassGraph                              I 2020-04-09T18:12:34.749+0200	ClassGraph	FallbackClassLoaderHandler did not find classpath entries in unknown ClassLoader com.ibm.ws.classloading.internal.GatewayClassLoader@5ec53685

[09.04.20 18:12:34:750 MESZ] 0000003d io.github.classgraph.ClassGraph                              I 2020-04-09T18:12:34.750+0200	ClassGraph	Classloader com.ibm.ws.classloading.internal.AppClassLoader@71f0b71c is handled by nonapi.io.github.classgraph.classloaderhandler.WebsphereLibertyClassLoaderHandler

[09.04.20 18:12:34:750 MESZ] 0000003d io.github.classgraph.ClassGraph                              I 2020-04-09T18:12:34.750+0200	ClassGraph	Ignoring duplicate classpath element: /WEB-INF/classes

[09.04.20 18:12:34:750 MESZ] 0000003d io.github.classgraph.ClassGraph                              I 2020-04-09T18:12:34.750+0200	ClassGraph	Ignoring duplicate classpath element: /Users/msimons/.m2/repository/io/github/classgraph/classgraph/4.8.68/classgraph-4.8.68.jar
```

That liberty Maven thing does something weird with `WEB-INF/classes` it seems. 

The same plugin can produce a runnable jar with `mvn liberty:package -Dinclude=runnable` that can be started with `java -jar target/ServletSample.jar`. Going to http://localhost:9080/ServletSample/servlet shows you now the correct number of classes found (1).

[classgraph-on-liberty.zip](https://github.com/classgraph/classgraph/files/4457386/classgraph-on-liberty.zip)
[messages.log](https://github.com/classgraph/classgraph/files/4457392/messages.log)

The logs are under `target/liberty/wlp/usr/servers/guideServer/logs`.

**Comment by lukehutch** [comment]
Hi Michael,

Thanks for the bug report.

I don't know if the classes you're looking for are in the `ThreadContextClassLoader` or one of the two classloaders that are shown as unsupported.

Can you please determine which classloader is responsible for loading the classes in question?

(1) If it is `ThreadContextClassLoader`:

(a) Please see `WEB-INF/classes` to see whether the classes are in this detected classpath element. 

(b) If not, please set a breakpoint in `WebsphereLibertyClassLoaderHandler`, and examine the `ThreadContextClassLoader` instance to find missing classpath elements.

(2) If it's one of unsupported classloaders `GatewayClassLoader` or `AppClassLoader` (actually whether it is or not), I'd really appreciate it if you could please write a `ClassLoaderHandler` for those classloaders. It's much easier for you to do that than me, because it's very time consuming for me to learn how to get up and running on a new runtime environment and get it working with the debugger. 

Thanks!

**Comment by cpierceworld** [comment]
I am experiencing the same problem... deploying to liberty running in Eclipse.

Problem happens when application is deployed using "overlays". (i.e. not a war file)
In this scenario:
- classloader: "ThreadContextClassLoader"
  - has "SmartClassPath"
    - has delegate: "DirectoryBasedOverlayContainerImpl$OverlayDelegatingContainer"
      - has path: "/WEB-INF/classes"

But "/WEB-INF/classes" doesn't exist, it is supposed to map to "<maven_project>/target/classes"

The delegate "DirectoryBasedOverlayContainerImpl$OverlayDelegatingContainer" has its own delegate ("com.ibm.ws.artifact.loose.internal.LooseContainer").

Looking over the ibm code, the "SmartClassPath" has a "getClassPath" that returns all the URLs that makes up the classpath.   That calls "getContainerURLs" for all of its "ContainerClassLoader" entries, which calls "getURLs" for all its containers.

The container [getURLs](https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.javadoc.liberty.doc/com.ibm.websphere.appserver.spi.artifact_1.2-javadoc/com/ibm/wsspi/adaptable/module/Container.html?view=embed#getURLs()) method returns "A collection of URLs that represent all of the locations on disk that contribute to this container"

**Comment by lukehutch** [comment]
Can either of you please take a stab at fixing the `ClassLoaderHandler`? It's much easier for you to fix it than me, since you're already up and running on WebSphere Liberty. It's probably just a few lines of code.

**Comment by lukehutch** [comment]
@michael-simons I just merged the change from @cpierceworld. Can you please test to see if this fixes your issue too? Just `./mvnw install` ClassPath then depend upon the snapshot version that is built. Thanks!

**Comment by lukehutch** [comment]
Also, if either of you is feeling particularly ambitious, it would be great to have a `ClassLoaderHandler` for `com.ibm.ws.classloading.internal.GatewayClassLoader` and `com.ibm.ws.classloading.internal.AppClassLoader`. I have no idea if there are ever classes of interest loaded by these classloaders, but I hate seeing unsupported classloaders for major runtime environments.

**Comment by lukehutch** [comment]
@cpierceworld Please also verify that your changes don't break things when you're running a war file (not an overlay).

**Comment by cpierceworld** [comment]
> @cpierceworld Please also verify that your changes don't break things when you're running a war file (not an overlay).

I tested it deploying it as a war file as well.

**Comment by michael-simons** [comment]
> @michael-simons I just merged the change from @cpierceworld. Can you please test to see if this fixes your issue too? Just `./mvnw install` the master version of ClassPath, then depend upon the snapshot version that is built. Thanks!

Hi Luke. Will do later in the day. But honestly, the reproducer I attached in the first issue does all that. It already includes liberty etc.

**Comment by lukehutch** [comment]
> Hi Luke. Will do later in the day. But honestly, the reproducer I attached in the first issue does all that. It already includes liberty etc.

Thanks for the reproducer. I wasn't trying to be lazy about it... I have just learned from past experience on at least half a dozen occasions that it usually takes me several hours to figure out how to get the Eclipse debugger working with a new runtime environment to the point that I can reproduce the problem and see what's going on with custom classloaders. I really need community help and expertise for these tasks, because you guys can do it so much more quickly than me.

**Comment by lukehutch** [comment]
That said, I tried following your instructions anyway, and got this error on `mvn liberty:dev`:

```
[ERROR] Failed to execute goal io.openliberty.tools:liberty-maven-plugin:3.1:dev (default-cli) on project ServletSample: Could not get the highest version from the range: [19.0.0.6,): Unable to resolve version range fram io.openliberty:openliberty-kernel:zip:[19.0.0.6,) -> [Help 1]
```

I'm not sure what to fix, since this version number is not present in your `pom.xml`.

**Comment by michael-simons** [comment]
That's interesting and I'm sorry for that. I'm not an expert on Websphere / Open Liberty at all… Was a customer request. I downloaded my own reproducer on a different machine, unzipped it and was able to run with mvn liberty:dev as described. Could it be that you have some snapshot repos defined in a `settings.xml`? 

Anyhow, I have tested it now and I can confirm the latest classgraph master works as expected.

I tested it with 

* `io.openliberty:openliberty-runtime:18.0.0.4`
* `io.openliberty:openliberty-runtime:19.0.0.9`
* `io.openliberty:openliberty-runtime:20.0.0.4`

and for good measurement also with the full blown Websphere Runtime:

* `com.ibm.websphere.appserver.runtime:wlp-javaee8:19.0.0.9`
* `com.ibm.websphere.appserver.runtime:wlp-javaee8:20.0.0.4`

Look good to me.

**Comment by lukehutch** [comment]
> That's interesting and I'm sorry for that. I'm not an expert on Websphere / Open Liberty at all… Was a customer request.

Ah! Sorry, I didn't read your comment closely enough, and assumed you were an expert. Thanks for getting me the reproducer, and I appreciate you re-testing it.

> Could it be that you have some snapshot repos defined in a `settings.xml`?

Sonatype snapshots are enabled, yes, but you have to have `-SNAPSHOT` in the version code to use those, I think. No idea what was causing the issue.

> Anyhow, I have tested it now and I can confirm the latest classgraph master works as expected.

Great! Thanks for confirming.

Released as 4.8.69. Thanks for the collaboration on this one, guys!

@RaimondKempees please try 4.8.69, due to the changes described above. I assume the new version will still work for you, based on Michael's tests, but I wanted to double check, since you wrote the original `ClassLoaderHandler`.

**Comment by michael-simons** [comment]
> Released as 4.8.69. Thanks for the collaboration on this one, guys!

100% Agree! Thanks to everyone.

**Comment by lukehutch** [comment]
@RaimondKempees and @cpierceworld, can you please comment on this too: is it worth supporting these classloaders? I don't know what their purpose is, so I don't know if classes of interest will ever be loaded by these two classloaders.

> Also, if either of you is feeling particularly ambitious, it would be great to have a `ClassLoaderHandler` for `com.ibm.ws.classloading.internal.GatewayClassLoader` and `com.ibm.ws.classloading.internal.AppClassLoader`. I have no idea if there are ever classes of interest loaded by these classloaders, but I hate seeing unsupported classloaders for major runtime environments.

**Comment by michael-simons** [comment]
Thanks again: I can confirm this works with Spring Data Neo4j + OGM on Liberty, too: https://github.com/michael-simons/neo4j-sdn-ogm-with-jax-rs/tree/master/sdn-on-liberty 👍

**Comment by lukehutch** [comment]
Great, thanks for letting us know.

**Comment by RaimondKempees** [comment]
@lukehutch as far as I can see (only did a 10 minute check) this is an addition and the original logic is preserved and used as needed, so looks good to me. Unfortunately can't test it real quickly though.

**Comment by lukehutch** [comment]
@RaimondKempees If the new method succeeds, the old method won't be used, and this could lead to undesirable behavior potentially (I have no idea). No problem though! Please report back if you ever run into issues.

**Comment by RaimondKempees** [comment]
@lukehutch no worries - will do. There's quite a few people using it, so we can fix quickly if needed.
