### ISSUE TITLE
invalid position of MANIFEST.MF

### ISSUE THREAD

**Issue by blackdrag** [classgraph/classgraph#417]
The MANIFEST.MF in a jar must be at the first or second position. The second position is valid iff the first position is the META-INF directory. It seems classgraph 4.8.56 is the last one that has this correct. I assume that https://github.com/classgraph/classgraph/commit/47972496b09af7b5b7251897d1f109a78dcfa5c0 is the cause of this problem. 

The result is that any jar tool and any jar based logic in the jdks is unable to find the manifest and its folder properly. Because the folder is not found properly the jar is not recognized as proper module, leading to a different module name and messing the build up when using the jigsaw multi module feature in gradle 6.4-rc1.

See for example https://github.com/Zlika/reproducible-build-maven-plugin/issues/16 for a discussion about the positioning.

**Comment by lukehutch** [comment]
Wow, that's a very unfortunate shortcut that the JDK developers took... I didn't know about that.

I used `git bisect` to find the problematic commit, and it was actually in the 4.8.66 development cycle, so this was a recent change. The commit in question, f7910a4ca9fba58e463863a3cabdb461cc3da2c7, stripped `<@m2e...@>` [directives](https://www.eclipse.org/m2e/documentation/release-notes-17.html#new-syntax-for-specifying-lifecycle-mapping-metadata) from `pom.xml`, since some tools can't handle them. For some reason the entire jar was being repackaged as a result of this change, even though only the `pom.xml` should have been extracted, modified, and re-added to the jar -- so the manifest file was getting moved as a side effect.

Fixed and released in 4.8.70. Thanks for the report!

**Comment by GedMarc** [comment]
Wow.

Ok... Different,
I came across something weird as well doing bouncy castle, the only class file allowed in the root package is module-info.class - i wonder if this has to do with that...
But it contains a class called "1.class", I never ClassGraph reflected onto it, ended up having to shade everything in, and add a manual exclude into onto the shade for it.

https://github.com/GedMarc/JWebMPDevKit/blob/3631dcdfba55f52bba4144abe278a2757812d2e4/GuicedEE/Services/commons/apache-cxf/pom.xml#L687

don't judge the pom

**Comment by lukehutch** [comment]
@GedMarc I need to start using your pom file as a stress test for large classpath scanning :-)

I don't understand what your question is though, can you please rephrase?

The default (empty) package is disallowed for classes contained in JPMS modules. If you try to create a class in the default package of a modular project in Eclipse, you are shown the error `Must declare a named package because this compilation unit is associated to the named module 'modulename'`.

ClassGraph will still pick up classes in the default package however -- probably it should not do that. I'll check in a change to fix this in a few minutes, but it's not worth pushing out a whole new release for this.

Please try to always open a new bug for an unrelated issue or feature request. Thanks!

**Comment by lukehutch** [comment]
@GedMarc the fix is in master for that issue you had with `1.class`.

**Comment by GedMarc** [comment]
Oh awesome thanks man!

Yup - this is what it currently looks like taking a framework, that has 68 dependencies, into a JLink artifact - everything up the chain has to have its own module and module-info
Deploying to central to get it to build..well, have to exclude all the defaults with their module ones..

Flip one day... jakarta is trying so hard you can see the module come in and out through commits....

But.. I can build and deploy a jlink rest module microservice in a container 20mb large with bells and whistles xD
