### ISSUE TITLE
BaseTypeSignature constants reference ScanResult and prevent GC

### ISSUE THREAD

**Issue by protogenes** [classgraph/classgraph#419]
The constants in BaseTypeSignature reference a ScanResult.

* As a result it cannot be garbage collected and after the fix for #399 the closed instance's remaining memory footprint has a gravely increased.
* In a concurrent situation when using multiple ScanResults this is not threadsafe
* It is confusing to have an eventually changing ownership of those constants

The ownership seems to be set up by method return types https://github.com/classgraph/classgraph/blob/d8c84dcb76a5a6bcf35c3280c373448e2b2b3646/src/main/java/io/github/classgraph/MethodTypeSignature.java#L236

Is the scanResult reference even required for the native type signatures? Maybe each static constant should be replaced with a value per ScanResult.

**Comment by lukehutch** [comment]
@protogenes Thanks for the report, and for your analysis.

It took me a while to figure out what you meant, since the `ScanResultObject#scanResult` field is not static, and I explicitly try to never use static fields for non-constant values. Then I realized that the `BaseTypeSignature` fields for each primitive type were in fact static, so their non-static fields become effectively static. Good catch!

There was no particular problem with the value of the `scanResult` field changing with each new scan, since that field is never used by `BaseTypeSignature`, since it doesn't need to get the `ClassInfo` object by name for any primitive types. But you're right, this field held a reference to the `ScanResultObject` of the most recent scan, for each primitive type, and this would leak memory after the `ScanResult` was closed.

Fixed and released in 4.8.72.
