### ISSUE TITLE
ClasspathFinder is reading bytes into memory and immediately throwing them away

### ISSUE THREAD

**Issue by nsoft** [classgraph/classgraph#421]
I ran into some OOM problems with a very large parent classpath even when I set the parent to be ignored. I discovered that the following code in ClasspathFinder.java is not quite ignoring the parent.

```
                    final LogNode classloaderHandlerLog = classloaderURLLog == null ? null
                            : classloaderURLLog
                                    .log("Ignoring parent classloader " + classLoader + ", normally handled by "
                                            + classLoaderHandlerRegistryEntry.classLoaderHandlerClass.getName());
                    classLoaderHandlerRegistryEntry.findClasspathOrder(classLoader, ignoredClasspathOrder, scanSpec,
                            classloaderHandlerLog);
```
This reads everything in the parent for the where the user is  ignoring parents, but scanning the entire java.class.path anyway (?). There are a number of settings under which the retained information is never used, and this just becomes a memory usage liability. (PR shortly)

As commentary, I think I would find it confusing to sort out the case where a class on the class path was loaded by the parent and then mysteriously didn't show up when I scanned the java.class.path... so I find that use case a bit dubious to begin with, but I imagine someone must have it.

**Comment by lukehutch** [comment]
I merged your PR (thanks for that), but then tweaked the logic a bit so that `java.class.path` is never scanned at all if `ClassGraph.ignoreParentClassLoaders()` is called. I think this will fix your issue, but please test the master version.

Also, I'm a little puzzled by why you would hit an OOM condition by just scanning classloaders, since the classloader scanning process simply compiles a set of classpath element paths. This should not consume all that much RAM even on a very large classpath, and it makes me wonder if one of the `ClassLoaderHandler` classes might be trying to recursively fetch classpath elements from a classloader's data structures in such a way that it gets stuck in an infinite loop. Can you please check on this with the unpatched latest released version of ClassGraph, just to make sure we're not wallpapering over another potential bug?

**Comment by nsoft** [comment]
The memory use likely related to the problems with my custom ClassLoaderHandler that was inapproriately resolving individual classes (also caused some issues seen in #423) because not only was I loading up an uno-jar full of user provided classes and dependencies, that was being done by jesterj which is a very very heavy fat jar with around 300 dependencies (196M, when double compressed) baked into it, so running through the parents and processing every class found there might have been a weee tad heavy :)... and the machine in question has only 16GB half of which is used by other progs... and I had had to raise the mem on JesterJ to 6GB before this... Also note that OneJar code I inherited (and am slightly suspicious of) pre-loads all the bytes for all the jars already, so... at a minimum I was holding two copies of 196M double inflated. (plus the user level fat jar). plus whatever horrible GC I caused :)

**Comment by lukehutch** [comment]
Right, ClassGraph should definitely not be causing the OOM. Literally the only thing a `ClassLoaderHandler` is supposed to do is extract classpath entry objects (`URL`, or `File`, or path `String`) from a `ClassLoader` instance, and put these into the correct order. That should not fill up RAM, especially since in most cases, the classpath objects are not copied, the reference obtained from the `ClassLoader` is just used directly. If ClassGraph is causing OOM, it's a big bug, but the only way it could do that is if a `ClassLoaderHandler` is getting stuck in an infinite loop, and also copying these classpath entry objects.

**Comment by lukehutch** [comment]
I'll assume the OOM issues are not due to ClassGraph, but rather the classloader loading all classfiles into RAM. I'm releasing this change (disabling `java.class.path` scanning if parent classloaders are disabled) in 4.8.78.
