### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by JBrVJxsc** [classgraph/classgraph#429]
hey @lukehutch, good day! I'm trying to use whitelistPackages to whitelist classes with the following packages: 1. the default package (no package); 2. com.foo.bar; do you know how should I achieve this? Thank you!

**Comment by lukehutch** [comment]
Hi, the default package is whitelisted as `""`, but usually the only way you would want to whitelist the default package is non-recursively, because if you call `.whitelistPackages("")`, it's the same as whitelisting nothing, i.e. all packages are scanned. Probably you want:

`new ClassGraph().whitelistPackagesNonRecursive("").whitelistPackages("com.foo.bar")`

Let me know if that works.

**Comment by JBrVJxsc** [comment]
@lukehutch thank you it worked! it saved a lot of memory and eliminated OOM!

**Comment by lukehutch** [comment]
Great! I'll close this. How large was your classpath, and how big is your heap?

**Comment by JBrVJxsc** [comment]
@lukehutch the heap was 128mb :)
