### ISSUE TITLE
Exception when deserializing from JSON

### ISSUE THREAD

**Issue by fluxroot** [classgraph/classgraph#431]
When deserializing from JSON, we get the following exception:

```
Exception in thread "main" java.lang.IllegalArgumentException: Expected integer; got java.lang.Long
	at nonapi.io.github.classgraph.json.JSONDeserializer.jsonBasicValueToObject(JSONDeserializer.java:112)
	at nonapi.io.github.classgraph.json.JSONDeserializer.populateObjectFromJsonObject(JSONDeserializer.java:479)
	at nonapi.io.github.classgraph.json.JSONDeserializer.populateObjectFromJsonObject(JSONDeserializer.java:602)
	at nonapi.io.github.classgraph.json.JSONDeserializer.populateObjectFromJsonObject(JSONDeserializer.java:602)
	at nonapi.io.github.classgraph.json.JSONDeserializer.populateObjectFromJsonObject(JSONDeserializer.java:602)
	at nonapi.io.github.classgraph.json.JSONDeserializer.populateObjectFromJsonObject(JSONDeserializer.java:602)
	at nonapi.io.github.classgraph.json.JSONDeserializer.populateObjectFromJsonObject(JSONDeserializer.java:602)
	at nonapi.io.github.classgraph.json.JSONDeserializer.deserializeObject(JSONDeserializer.java:681)
	at nonapi.io.github.classgraph.json.JSONDeserializer.deserializeObject(JSONDeserializer.java:708)
	at io.github.classgraph.ScanResult.fromJSON(ScanResult.java:1300)
	at classgraphjsonbug.Main.main(Main.java:9)
```

Even a simple program throws this exception:

```
package classgraphjsonbug;

import io.github.classgraph.ClassGraph;
import io.github.classgraph.ScanResult;

public class Main {
    public static void main(String[] args) {
        String json = scan();
        ScanResult scanResult = ScanResult.fromJSON(json);
    }

    private static String scan() {
        try (ScanResult scan = new ClassGraph()
                .verbose()
                .enableAllInfo()
                .scan()) {
            return scan.toJSON();
        }
    }
}
```

We've tested this code with the latest version 4.8.80 on the classpath. We have also attached the verbose output:

[classgraph-json-bug.txt](https://github.com/classgraph/classgraph/files/4732083/classgraph-json-bug.txt)

Can you tell us what we're doing wrong?

-- Poke

**Comment by lukehutch** [comment]
Hi, I cannot replicate this (see the above unit test that I added). Can you please catch the exception in a debugger, and see which class and which field is being deserialized when the exception is thrown?

**Comment by fluxroot** [comment]
I'm not familiar with your JSONDeserializer. But if I read the variables correctly, ClassGraph has a problem deserializing the field `private Integer integerValue;` of `io.github.classgraph.ObjectTypedValueWrapper`. The JSON value is Long, but I guess it should be an Integer.

I have attached a simple project. Just extract and run it with `./gradlew run`: [classgraphjsonbug.tar.gz](https://github.com/classgraph/classgraph/files/4734222/classgraphjsonbug.tar.gz)

**Comment by lukehutch** [comment]
Thanks! Fixed in 4.8.81.

I think you are the first users who tried to use the serialization / deserialization support :-)

**Comment by fluxroot** [comment]
I'm sorry, but I have to reopen this one again. Now we get another exception:
```
java.lang.IllegalArgumentException: Expected float; got out-of-range value 0.0
```
You can reproduce this by setting `static final float g = 0.0f;` in `Issue431Test`.

**Comment by lukehutch** [comment]
@fluxroot No problem; sorry for the trouble.

I pushed a fix to git master. Can you please try this version, and let me know if all the remaining issues are resolved before I push out another version? Thanks.

**Comment by fluxroot** [comment]
Yay! Looking good. We will do more testing tough as this is critical for us to get right. Thanks for the fixes!

**Comment by lukehutch** [comment]
Great! Let me know.

Note that for most usecases, you don't need all the information in the `ScanResult`. If you take a look at your serialized version, you'll see it can get very large. It's usually much more efficient (in both time and memory) to query the `ScanResult` for information you need, then write out a smaller JSON file that contains only the information of interest. 

The reason I wrote a custom JSON serializer and deserializer for ClassGraph is that the graph of objects reachable from `ScanResult` contains many cycles and cross-links. This is generally not supported by JSON serialization libraries. You'll note the `__ID` field added to many JSON objects by the ClassGraph serializer -- these are objects linked to more than once. When a field should contain an object but instead uses one of these IDs, it is turned into a direct reference.

**Comment by lukehutch** [comment]
Fixed and released in 4.8.82. Thanks for the bug report!

With this change, the diff will still fail to show identity between the old and new JSON, but the only difference that should be detected is the `overrideClasspath` field value for the `ScanSpec` JSON object. The reason this is different is that when you re-create a `ScanResult` from JSON, the override classpath is set so that classloading loads classes in the same order as the original `ScanResult`. Everything else should be identical.

**Comment by lukehutch** [comment]
I just saw your Gitter message that the `overrideClasspath` setting causes the classes to load with the wrong classloader. I can disable this -- I guess there are more ways that this can go wrong than ways it can fix other problems that can arise.

**Comment by lukehutch** [comment]
@fluxroot Fixed and released in 4.8.83. Serializing and then deserializing a `ScanResult`, and then re-serializing it, should produce exactly the same result now, and the classpath is not overridden.

**Comment by fluxroot** [comment]
@lukehutch Nice, thanks for this change! We ran some tests and it's looking real good. Functionally I'd say serialization is quite stable. The only two problems we currently have are memory consumption and execution time of deserialization. But that's something we need to analyze more in-depth. Thanks again for your work!

**Comment by lukehutch** [comment]
@fluxroot You're welcome, thanks for the reports!

The extra memory overhead on deserialization is probably because the deserializer works in a 2-step process: the entire JSON file is read into a generic JSON object structure, then that structure is mapped onto the class hierarchy to instantiate and populate each relevant object. Those two steps could be combined into one, however that would be a complex code transformation, because the recursive structure of the object deserializer would have to be joined with the recursive structure of the recursive descent parser -- and I don't know if there would be a 1:1 match.

The serializer and deserializer could be sped up by a large factor by replacing introspection with `MethodHandle` calls. That was always on the TODO list, but I never got it done, because I spent a lot of time working on the serializer and deserializer, but right as soon as I finished them, I realized that for the vast majority of usecases, serializing the entire `ScanResult` and all linked objects was extremely inefficient, and probably completely unnecessary. For most usecases, you only care about some subset of a `ScanResult`, and that's all you need to write out to a file, i.e. you just need to write out the result of a specific query or set of queries on a `ScanResult`, not the whole `ScanResult`.

So I'm curious: why do you want to serialize the whole `ScanResult`, and not simply the results of a specific query against a `ScanResult`?

See this too:

https://github.com/classgraph/classgraph/wiki/Build-Time-Scanning

**Comment by fluxroot** [comment]
@lukehutch Thanks for your in-depth explanation. Exactly this page got us the idea of using serialization to speed up application initialization.

Because we scan the classpath multiple times using different parameters, we thought serializing a big ScanResult and filtering afterward would be a good idea. This way we would read from disk only once and process further classpath queries fast in memory.

Unfortunately, we have an extension mechanism that requires us to scan the classpath at runtime. Besides, serializing queries at build time would mean putting application logic into build logic and pass that information all the way to the web application. This could be done, but in our opinion, it is highly complex, and maintaining such a solution requires great effort.

So if deserializing would be blazingly fast and resource-friendly, I think we would take this path. But for now, it's better for us to just hit the disk and go from there.

**Comment by lukehutch** [comment]
You could try Jackson, although I don't think it properly handles cycles in the object graph. It is much faster though, because it uses MethodHandle etc.

**Comment by lukehutch** [comment]
You're also welcome to optimize the serializer and deserializer. I anticipate a 2-10x speedup could be achieved. The code is a bit complex though.
