### ISSUE TITLE
package io.github.classgraph.utils.FileUtils does not exist

### ISSUE THREAD

**Issue by SudBisht** [classgraph/classgraph#454]
Earlier it was working fine, certainly stopped working
FileUtils.java not present in the latest release(onwards 4.8.83), 

Thank you!

**Comment by lukehutch** [comment]
Please provide more info. What is the problem exactly?

**Comment by lukehutch** [comment]
`io.github.classgraph.utils.FileUtils` is not a package, it's a class. Where are you seeing this? I don't know why you didn't provide a description, or a stacktrace, or any more info. Please provide a complete bug report.

**Comment by SudBisht** [comment]
after using an old version (4.0.2), the issue is resolved

**Comment by lukehutch** [comment]
I strongly recommend not using an old version. Many problems were fixed since then.

Also, that class is definitely present in all recent versions of ClassGraph. Maybe you needed to do a clean before build?

Please provide a stacktrace for the problem.

**Comment by SudBisht** [comment]
it's a compile-time error:
`error: package io.github.classgraph.utils does not exist
import io.github.classgraph.utils.FileUtils;`

the latest version doesn't have the package `utils` class.
<img width="526" alt="Screenshot 2020-06-26 at 9 40 42 AM" src="https://user-images.githubusercontent.com/6227302/85819516-8784f500-b791-11ea-8482-ddb5a18c4b49.png">

**Comment by lukehutch** [comment]
The package does exist (you can look at the jar manually to verify), but it's not exported in a JPMS or OSGi environment, because nothing in that package is supposed to be exposed as part of the ClassGraph API. Classgraph'S own classes should be able to call that class though. Are you using a modular project or module path? What JVM version are you using?

Do you see any info about which class is trying to load the `FileUtils` class?

**Comment by SudBisht** [comment]
I am using that class directly in my code, like: 
`String content = FileUtils.readAllBytesAsString(inputStream, -1L, null);`

**Comment by lukehutch** [comment]
Oh! Well you can't do that. `FileUtils` is not part of the public API of ClassGraph. Where did you get the idea to call that method? Hopefully there are no code examples on the ClassGraph Wiki that tell users to use that class. It's internal-only.

Note that the class is not `io.github.classgraph.utils.FileUtils`, it's `nonapi.io.github.classgraph.utils.FileUtils` -- specifically telling users that it's not an API class. Nothing in `nonapi.*` is exported in the module descriptor, so other projects can't call anything in `nonapi.*`. This is by design.

**Comment by lukehutch** [comment]
Feel free to just copy and paste this method into your own code if you want. But actually in JDK 11, you should be using `Files.readAsString(Path)` anyway.
