### ISSUE TITLE
JAR file names with a + in them fail to get scanned

### ISSUE THREAD

**Issue by adelel1** [classgraph/classgraph#468]
Hello,

We have a JAR file name that contains a + character in it. And it is failing to get scanned.
After a bit of debugging its failing because the URLDecoder.decode function in Scanner.java is replacing the + with a space. It then tries to load this file, but that fails as there is no filename with a space in it.

We are passing in a URL to ClassGraph, we create the URL we pass in, via 

it.toUri().toURL()

where 'it' is a Path.

We have no control over the filenames used so we really need support for filenames with a + in them as well.

Regards, Adel

**Comment by lukehutch** [comment]
Looks like this is a known bug...

https://bugs.openjdk.java.net/browse/JDK-8179507

I'll replace that function.

**Comment by lukehutch** [comment]
@adelel1 Can you please test the latest version in git, it should solve the problem.

**Comment by adelel1** [comment]
Thanks for the quick response, yes will do.

**Comment by adelel1** [comment]
Hello,
While testing this I've noticed a behaviour change/bug introduced in 4.8.85 (due to #435 possibly), I didn't notice it earlier as I think I must have put the issue down to the + sign being present in the file.

Anyway in 4.8.85 none of my jars are getting scanned. The problem is ClassGraph.filterClasspathElements has changed.
The path passed to ClasspathElementFilter now does not contain the initial 'file:' , prior to 4.8.85 it did, so my string comparison failed and the wrong boolean was returned in the filter and so nothing was scanned. Is this a bug?

After changing the comparison, I do see the files with the + sign in them being scanned correctly. So the original issue looks resolved.

regards,

**Comment by lukehutch** [comment]
Thanks for testing. 

For the other bug, can you please attach full verbose logs (call `.verbose()` before scanning), for versions of ClassGraph before and after the change?

**Comment by adelel1** [comment]
[cgissue.zip](https://github.com/classgraph/classgraph/files/5109935/cgissue.zip)

I have uploaded a simple Java project that shows the problem. In root of project are 2 files verbose84.txt and verbose85.txt, at the top of the file you will see the difference. In verbose84 it contains file:/...., while in verbose85 it does not.

To run the project use './gradlew run' in the top level dir.

**Comment by lukehutch** [comment]
Thanks for the test project. It looks like the classes that are found in both cases are identical. Was your only concern that the `file:` prefix was dropped, or was there a behavioral difference? Technically the `file:` prefix is optional on local paths in the classpath, so stripping that from paths should not affect anything.

**Comment by adelel1** [comment]
Hello, yes it was just regarding the file: prefix. OK, its not a problem, I will check for both in the filter function.
Will you be doing a new release for the + fix.
Thanks,

**Comment by lukehutch** [comment]
I see -- it's only in `.filterClasspathElements()` that the path will have `file:` stripped. The Javadoc already explains that the prefixes will be stripped. I made the change for consistency, since files and dirs may or may not have `jar:` and/or `file:` schemes, and `.filterClasspathElements()` filters based on path string.

I released 4.8.88 with the fix to the `+` character issue, however after releasing that I committed a further change that adds a new `ClasspathElementURLFilter` that you can pass into `.filterClasspathElements()` rather than a `ClasspathElementFilter`. The new filter type gets the full `URL` for each classpath element, which should include the `file:` prefix, and possibly also a `jar:` prefix before that. Note however that these are "raw" URLs that are obtained from the ClassLoader(s), so you may get some variation in the exact syntax (e.g. there may or may not be a `jar:` prefix). Please try the latest git version and let me know if you prefer this filter type, and if so, I can push out 4.8.89 with this feature.

**Comment by adelel1** [comment]
Thanks for releasing 88 with the fix. I have tried 89-SNAPSHOT with the new URL filter element and it works fine for me. I will most likely use this new filter. So if you can release 89 that would be good, to contain both old string and new URL filter.
Thanks

**Comment by lukehutch** [comment]
Released as 4.8.89. Note that I renamed `￼filterClasspathElements(ClasspathElementURLFilter)` to `filterClasspathElementsByURL(ClasspathElementURLFilter)`, so that there's no method ambiguity if you use untyped lambda expressions.

**Comment by adelel1** [comment]
Thats great, thanks for the quick response.

**Comment by lukehutch** [comment]
You're welcome! I appreciate the followup.
