### ISSUE TITLE
Scanning for locally compiled classes (exlude child classes)

### ISSUE THREAD

**Issue by wheelerlaw** [classgraph/classgraph#486]
I am trying to figure out how to accomplish this, but so far from reading the documentation I have not been able to figure it out. 

Basically, I want to scan for all classes that have been compiled locally by Maven or Gradle or something. I sort of figured out how to do it by doing this:

```java
		List<String> classnames = new ClassGraph()
			.acceptPackages("")
			.disableJarScanning()
			.rejectClasses(Closure.class.getName())
			.scan()
			.getAllClasses()
			.getNames();
```

Since I'm doing this on Groovy classes, I am getting a ton of extra classes that represent the Groovy closures in many of the classes. For example (the highlighted classes in this list of variables in IntelliJ are closure classes):

![image](https://user-images.githubusercontent.com/3081566/101587054-4edc7f00-39b1-11eb-9b84-b2627c054bdb.png)

What I want to do is exclude classes that have `groovy.lang.Closure` as their super class (or at any other arbitrary location below the class in the class hierarchy). 

I tried using `rejectClasses`, but closures are compiled into anonymous classes that extend `groovy.lang.Closure` instead of being an instance of a `Closure`, and it seems that `rejectClasses` only works the provided class itself. 

Is there a way to do this that I am overlooking?

Thanks

**Comment by lukehutch** [comment]
Hi, I recommend limiting the scan as closely as possible to what you want using `accept...` and `reject...` methods as you have done, and then using the methods of `ClassInfoList` to apply the more complex filtering logic that you require (e.g. removing all classes that have `groovy.lang.Closure` as a superclass). In fact you could do that directly using the following tweak to your query, but there are many other ways to execute more complex filtering logic after the scan is complete, by querying the `ScanResult` multiple times and [using intersection / union methods](https://github.com/classgraph/classgraph/wiki/ClassInfo-API#classinfolist), etc.

```
try (ScanResult scanResult = new ClassGraph()
    .acceptPackages("")
    .disableJarScanning()
    .rejectClasses(Closure.class.getName())
    .scan()) {
        List<String> classnames = scanResult
                .getAllClasses()
                .filter(ci -> !ci.extendsSuperclass(Closure.class.getName()))
                .getNames();
        // ...
}
```

Also note that you want to assign the `ScanResult` in a [try-with-resources block](https://github.com/classgraph/classgraph/wiki/ScanResult-API#scanresult-lifecycle), or `withCloseable` in Groovy.

Let me know if this works for you.

**Comment by wheelerlaw** [comment]
Awesome, I ended up finding that solution and it works like a dream. Thank you. 

However, I have run into another issue. So I am using this in a function that gets passed an parameter of type `Optional<Class<?>>` that will be evaluated and passed to a filter with `extendsSuperclass` similar to what I did above (only this time its not negated), for the purpose of filtering on classes that extend a specified type. However, it looks like `ClassInfo#extendsSuperclass` does not work if the parameter for `extendsSuperclass` is `Object.class.getName()` because if a class does not extend anything explicitly, `ClassInfo#getSuperclasses` returns an empty list (instead of a list containing a single element representing `java.lang.Object`). Is there a reason why this would be the case?

Perhaps an example would help. Lets say I have the following code:

```
		Optional<Class<?>> supertype = Optional.empty(); // this is just an example of the parameter not being set (or being set to `Optional.empty())

		List<String> classnames = new ClassGraph()
			.acceptPackages(_package.orElse(""))
			.disableJarScanning()
			.scan()
			.getAllClasses()
			.filter(ci -> !ci.extendsSuperclass(Closure.class.getName()))
			.filter(ci -> ci.extendsSuperclass(supertype.orElse(Object.class).getName()))
			.getNames();
```

I guess I would expect it to return the same count of classes if I removed the `.filter(ci -> ci.extendsSuperclass(supertype.orElse(Object.class).getName()))` line, since all classes extend `Object` one way or another. The way I have the code written allows for the parameter to be set to specify a class, or to not be set at all (implying that the search include all classes)

But instead of returning the same list of class names, it's an empty list. 

(and yes I did not include the try-with-resources block, since this is just a contrived example)

**Comment by lukehutch** [comment]
You're right, this was an oversight. `java.lang.Object` is the superclass of all standard classes, so it is not returned (for simplicity) by `ClassInfo#getSuperclasses()`, otherwise you'd have to filter it out or manually ignore it more often than not. In the process of ignoring `java.lang.Object`, I forgot to add special case handling to always return `true` if `"java.lang.Object"` is passed into `extendsSuperclass`.

Should be fixed in the latest git commit. Can you test please? Just use `./mvnw install` then depend upon the `-SNAPSHOT` version that is built.

Let me know if you have any other bugfixes or feature requests -- I'll wait until you get your usecase totally working before I push out a new version.

**Comment by wheelerlaw** [comment]
Hmm, while I think is a suitable fix for now, I'm not entirely sure not including `java.lang.Object` in `getSuperclasses()` is the right choice. Obviously you know this library much better than I do, but this seems to be a slight deviation from what I would expect an apposite Java API would do. 

I'm basing this off of the related behavior of the `getSuperclass` method. It returns `null` if the superclass is `java.lang.Object`. This doesn't correspond with `java.lang.Class#getSuperclass`, which returns `java.lang.Object` if that is the superclass. It is only until `java.lang.Class#getSuperclass` is called on `java.lang.Object` is `null` then returned. 

So just extrapolating from this observation, I would imagine that if the Java API had a method called `java.lang.Class#getSuperclasses`, `java.lang.Object` would be in that list. And so if there is a correspondence between your API and a hypothetical Java API, then I would think that `ClassInfo#getSuperclasses` would also return a list that had `java.lang.Object` as an element. Just my take on it. 

In any case, the fix worked. I do have to say that of all of the many, many projects I have interacted with I don't think I've ever gotten the kind of response time and push to deliver a fix that I have here. You clearly take the zero bug pledge seriously, and it's much appreciated. Thank you.

**Comment by lukehutch** [comment]
You're welcome -- like you I have interacted with many, many open source projects over many years, and it has been one disappointing experience with unresponsiveness after another, so I try to be responsive, at least to bug reports (feature requests I don't have a lot of time for right now, but if there's a bug, I try to get the fix turned around in 24 hours...).

I made the decision to remove `java.lang.Object` from results way back in the beginning of this project, because tons of code that actually used this library had to manually filter out or ignore `Object` or its methods. I figured that almost 100% of the time, you don't care about `Object` or its methods, because literally every standard class has those. So it was simpler making ClassGraph elide that information than thousands of users having to manually skip or ignore it. At least this is true of the "upwards" view (towards superclasses) -- but as you have found out, the "downwards" view (towards subclasses) is a different matter. There was already code in place for finding all subclasses of `Object`, but I missed one spot, which is what you found.

Yes, this is different from the way that the Java reflection API works. It's one of the few ways that ClassGraph works differently than the reflection API. But I think it's more useful in the long run, at least it saves a lot of people a bit of boilerplate code.

Since the current fix works for you, I'll release this as 4.8.94. Thanks for the report!

**Comment by lukehutch** [comment]
I just made another change that returns `true` from `￼extendsSuperclass("java.lang.Object")` only for standard classes, not for interfaces or annotations, since these do not extend `Object`. This will be in 4.8.95.

**Comment by wheelerlaw** [comment]
Fantastic, much appreciated.

**Comment by lukehutch** [comment]
Just as a heads-up -- Sonatype has issues with publishing artifacts right now, so I can't push to Maven Central until that is resolved. Feel free to use a locally-built snapshot until that is fixed. Also since I couldn't push 4.8.94, I'll just combine that change from the previous comment and release the final version as 4.8.94 with all changes.
