### ISSUE TITLE
How to show a relationship with static call inside a method?

### ISSUE THREAD

**Issue by tivrfoa** [classgraph/classgraph#508]
Hi!

classgraph is very cool!

I'm testing it, but I don't know how to make classgraph show the relationship between Animal and Util below:

```java
package com.lsc.domain;

import com.lsc.util.Util;

public class Animal {
    public Animal() {
        System.out.println(Util.iAmUseful());
    }
}
```

https://github.com/tivrfoa/java-class-graph

Is there a way to show that, please?

```java

    private static void testClassGraph() {
        String pkg = "com.lsc";
        try (ScanResult scanResult =
                new ClassGraph()
                    .verbose()               // Log to stderr
                    .enableAllInfo()         // Scan classes, methods, fields, annotations
                    .enableInterClassDependencies()
                    .acceptPackages(pkg)     // Scan com.xyz and subpackages (omit to scan all packages)
                    .scan()) {               // Start the scan
            ClassInfoList allClasses = scanResult.getAllClasses();
            try {
                // then dot -Tsvg < classgraph.dot > classgraph.svg
                String generateGraphVizDotFile = allClasses.generateGraphVizDotFile(500, 500);
                Files.write(Paths.get("classgraph.dot"), generateGraphVizDotFile.getBytes());
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
```

**Comment by lukehutch** [comment]
Thanks! Is there any chance you could please put together a tiny but complete testcase project that reproduces the problem? My first thought was that you might need `.ignoreClassVisibility()`, but since `Animal` and `Util` are in different packages, that shouldn't be the problem. But without the `Util` class, I can't necessarily reproduce this issue.

**Comment by tivrfoa** [comment]
> Thanks! Is there any chance you could please put together a tiny but complete testcase project that reproduces the problem? My first thought was that you might need `.ignoreClassVisibility()`, but since `Animal` and `Util` are in different packages, that shouldn't be the problem. But without the `Util` class, I can't necessarily reproduce this issue.

https://github.com/tivrfoa/java-class-graph

**Comment by lukehutch** [comment]
Thanks for providing the project. I worked on this so long ago that I forgot how it worked. The method you want is actually `.generateGraphVizDotFileFromInterClassDependencies()`, not `.generateGraphVizDotFile()`. 

The problem is that in this case, the reference to `Util` in the `Animal` class is in the bytecode of the method, which ClassGraph does not parse (because ClassGraph is focused only on class metadata, not code blocks). So ClassGraph is able to find that `Animal` references `Util` (because `Util` is mentioned as a class name in the constant pool of the `Animal` class), but there is no way for ClassGraph to know exactly what the relationship is between `Animal` and `Util`, other than that `Animal` somehow depends upon `Util`, short of parsing the bytecode (which I don't think ClassGraph will ever attempt to do).

Therefore, I created the method `.generateGraphVizDotFileFromInterClassDependencies()` for showing inter-class dependencies. It's simpler in its depiction than the regular `.generateGraphVizDotFile()`, in that it only shows an arrow from a dependant class to a dependency -- it doesn't attempt to show what type of relationship it is, by using an arrow.

Here is what the output of this method is, using the current release of ClassGraph:

<img width="302" alt="graph" src="https://user-images.githubusercontent.com/811305/112597193-6b6ebc80-8dd2-11eb-9f45-bdd23e225ec1.png">

So this is working as intended. Apologies for the confusion, and for having you put together the test project when I should have realized it was not needed!

Thanks for your report.

**Comment by lukehutch** [comment]
PS I updated the documentation on this:

https://github.com/classgraph/classgraph/wiki/ClassInfo-API#generating-a-graphviz-dot-file-for-class-graph-visualization

**Comment by tivrfoa** [comment]
> Thanks for providing the project. I worked on this so long ago that I forgot how it worked. The method you want is actually `.generateGraphVizDotFileFromInterClassDependencies()`, not `.generateGraphVizDotFile()`.
> 
> The problem is that in this case, the reference to `Util` in the `Animal` class is in the bytecode of the method, which ClassGraph does not parse (because ClassGraph is focused only on class metadata, not code blocks). So ClassGraph is able to find that `Animal` references `Util` (because `Util` is mentioned as a class name in the constant pool of the `Animal` class), but there is no way for ClassGraph to know exactly what the relationship is between `Animal` and `Util`, other than that `Animal` somehow depends upon `Util`, short of parsing the bytecode (which I don't think ClassGraph will ever attempt to do).
> 
> Therefore, I created the method `.generateGraphVizDotFileFromInterClassDependencies()` for showing inter-class dependencies. It's simpler in its depiction than the regular `.generateGraphVizDotFile()`, in that it only shows an arrow from a dependant class to a dependency -- it doesn't attempt to show what type of relationship it is, by using an arrow.
> 
> Here is what the output of this method is, using the current release of ClassGraph:
> 
> <img alt="graph" width="302" src="https://user-images.githubusercontent.com/811305/112597193-6b6ebc80-8dd2-11eb-9f45-bdd23e225ec1.png">
> 
> So this is working as intended. Apologies for the confusion, and for having you put together the test project when I should have realized it was not needed!
> 
> Thanks for your report.

Thank you very much!!!
