### ISSUE TITLE
Wildcard support in acceptClasses / rejectClasses

### ISSUE THREAD

**Issue by cushon** [classgraph/classgraph#536]
The docs for `acceptClasses` and `rejectClasses` mention

> May not include a glob wildcard (*).

Is this something you'd consider supporting in the future, or are there fundamental reasons why it isn't supported?

My use-case is scanning large jars for classes annotated with a particular annotation, and I'm seeing some OOMs. The annotated classes aren't necessarily in the same package, but they all follow a naming convention and have the same suffix, so it would be useful to be able to filter for names matching that suffix with something like `acceptClasses("*Suffix.class")`.

**Comment by lukehutch** [comment]
Actually the documentation might be wrong:

https://github.com/classgraph/classgraph/blob/latest/src/main/java/nonapi/io/github/classgraph/scanspec/ScanSpec.java#L71

https://github.com/classgraph/classgraph/blob/latest/src/main/java/nonapi/io/github/classgraph/scanspec/AcceptReject.java#L242

Did you test globs? As far as I can tell (or remember), globs should be supported. I think they weren't in earlier versions, and somebody requested this before. If that's the case, only the Javadoc needs changing.

Please let me know if it works!

**Comment by cushon** [comment]
Thanks for the response! I tried it and got an exception, I think it's hitting the assertion here:

https://github.com/classgraph/classgraph/blob/4e347fa2718f23d87425228f76a750dbd60a1dde/src/main/java/io/github/classgraph/ClassGraph.java#L924

**Comment by lukehutch** [comment]
Oh, oops! Please try deleting this check and building (`./mvnw install`). I don't think there's any reason why this shouldn't work, but I'm not certain of that.

**Comment by lukehutch** [comment]
Oops, sorry, accidentally clicked Close...

I just realized that it's possible that I disabled it because it doesn't work yet, because the hierarchical scanner may not yet have been prepped to be able to properly recursively descend to packages that contain specifically whitelisted classes. If you search for `*Suffix.class`, the `*` would have to cause the scanner to recursively descend into all packages. ClassGraph intentionally does not scan packages that cannot possibly contain an "accepted" class. So there may have to be some special logic put in place for this. (I say "may have to" because it has been so long since I wrote this code, and I will be traveling for the next week, so I can't easily check it.)

**Comment by cushon** [comment]
Just disabling that assertion wasn't enough to get `*Suffix` to work. Adding a second glob for the package part like `*.*Suffix` seems to have the behaviour I want, since it gets split on `.` into a package part and class part, and the first wildcard allows it to match all packages.

So that'd be sufficient for my use-case, but having special logic to allow `*Suffix` to work could be more intuitive.

**Comment by lukehutch** [comment]
@cushon Sorry for the delay, I was moving to a new apartment...

I removed the exception line, and explained in the JavaDoc the need for including the package name as a glob. (I think documenting this is sufficient, because any other change would be complex.) Can you please double-check that this is the same change you made, and that this should work? Then I'll push out a new release.

**Comment by cushon** [comment]
Yes, that matches the change I tried, thanks!

**Comment by lukehutch** [comment]
Thanks for your response, and for the bug report -- released as 4.8.111!
