### ISSUE TITLE
Fragile reference to private synthetic this$ field

### ISSUE THREAD

**Issue by cushon** [classgraph/classgraph#570]
The following code is using reflection to access a field with a name starting with `this$`:

https://github.com/classgraph/classgraph/blob/0682df0e067cc1662f9d722afde7a1c27eb974dc/src/main/java/nonapi/io/github/classgraph/classloaderhandler/JBossClassLoaderHandler.java#L228-L229

The OpenJDK javac generates private synthetic fields with names starting with `this$` as an implementation detail of inner classes. In the future that implementation detail may be changing, and the `this$` field will no longer be generated for all inner classes. For more information about the proposed change, see: https://bugs.openjdk.java.net/browse/JDK-8271717

Please consider alternatives to accessing the private synthetic `this$` field to ensure this code continues to work after the change. For example, consider passing an explicit copy of the enclosing instance to code that needs access to it, or adding an explicit getter to the inner class.

For example, given:

```java
class Outer {
  int x;
  class Inner1 {
    int f() {
      return x;
    }
  }
  class Inner2 {
    void g() {
      System.err.println("hello");
    }
  }
}
```

Currently `Inner1` and `Inner2` both have a synthetic field named `this$0` that stores a reference to `Outer`.

In the future the implementation detail might be changing to omit the field from classes that don't reference the enclosing instance. So in the example, `Inner1` would still have the synthetic field because it accesses the field `x` in the enclosing instance `Outer`. However `Inner2` would no longer have a synthetic field, because it doesn't access any state from its enclosing instance.

**Comment by lukehutch** [comment]
Hey, thanks for the info, this is a good heads-up. How did you find this? (Is ClassGraph in use at Google? I'm a Xoogler...)

If I follow the logic in the OpenJDK bug you referenced, synthetic accessor fields like `this$0` are only going to be removed if they are not referenced anywhere in the inner class. For the `JBossClassLoaderHandler` implementation that you linked, this would only happen if `org.jboss.modules.ModuleClassLoader$LocalClassLoader` doesn't refer to its outer class `org.jboss.modules.ModuleClassLoader` anywhere in its implementation -- and I suspect it would not be possible to implement `LocalClassLoader` without retaining a reference to its `ModuleClassLoader`.

I checked the implementation here:

http://www.javased.com/?source_dir=jboss-modules%2Fsrc%2Fmain%2Fjava%2Forg%2Fjboss%2Fmodules%2FModuleClassLoader.java

The code is question is 

```java
public class ModuleClassLoader extends ConcurrentClassLoader { 
     private final LocalLoader localLoader = new LocalLoader() { 
        public Class<?> loadClassLocal(final String name, final boolean resolve) { 
            try { 
                return ModuleClassLoader.this.loadClassLocal(name, resolve);    // (*)
            } catch (ClassNotFoundException e) { 
                return null; 
            } 
        } 
 
        public Package loadPackageLocal(final String name) { 
            return findLoadedPackage(name);    // (*)
        } 
 
        public List<Resource> loadResourceLocal(final String name) { 
            return ModuleClassLoader.this.loadResourceLocal(name);    // (*)
        } 
 
        public String toString() { 
            return "local loader for " + ModuleClassLoader.this.toString();    // (*)
        } 
    };
    // ...
}
```

So this is basically a proxy class, and every method requires `this$0` (see the lines marked `// (*)`), therefore this synthetic field would not be elided by a future version of javac, and there would be no problem for this particular case.

If this changes in future, the `JBossClassLoaderHandler` class would have to be changed anyway to support whatever new structure they change these classloaders to use -- but this is a separate issue from the `this$0` issue that you raise.

It's a broader question though as to whether there might be other compilers out there that generate synthetic members with a different naming convention -- I ran into some issues with IBM Semeru recently, where they changed the names of a bunch of internal fields and methods, for no apparent reason, relative to upstream OpenJDK (in particular they don't seem to like names that end with `0`, e.g. `Class.getDeclaredMethods0` -- they renamed this to `Class.getDeclaredMethodsImpl` -- so maybe they would change `this$0` to something else too...).

Did I understand the issue correctly?

**Comment by cushon** [comment]
Thanks for taking a look at this!

> How did you find this? (Is ClassGraph in use at Google? I'm a Xoogler...)

I found this by looking for occurrences of `"this$` in the source code of OSS projects. (ClassGraph is used a bit at Google--there's some other OSS code we use that depends on it, and it also supported JDK 11 earlier than some other classpath scanning libraries :)

> synthetic accessor fields like `this$0` are only going to be removed if they are not referenced anywhere in the inner class

Right, that's exactly it. I agree it looks like `ModuleClassLoader` is explicitly referencing the enclosing instance, so it will not be affected by this change.

I'd still recommend avoiding references to `this$` where possible since it's an implementation detail that isn't guaranteed by the spec, but in this specific case I'm not sure what the alternatives would be, since I'm guessing `ModuleClassLoader` doesn't provide a way to get the information you need from its public API.

> It's a broader question though as to whether there might be other compilers out there that generate synthetic members with a different naming convention

I checked and it looks like ecj uses the same naming convention. I'm not sure about other source-to-bytecode compilers, though.

**Comment by lukehutch** [comment]
> Thanks for taking a look at this!

Thanks for reporting it!

I suspect in most cases, `this$0` will not be elided by javac anywhere that it is actually in use, because it's rather silly to create a non-static inner class if you don't need access to the outer class (since if you program in the normal way, you get all these errors about trying to refer to instances of the inner class without a reference to the enclosing outer class, etc.).

> I found this by looking for occurrences of `"this$` in the source code of OSS projects.

I do miss the source code search tool at Google!

> (ClassGraph is used a bit at Google--there's some other OSS code we use that depends on it, and it also supported JDK 11 earlier than some other classpath scanning libraries :)

Awesome to hear. I tried to get a bunch of different open source libraries added to google3 when I was at Google, and almost every single time I gave up after days of wrangling with Blaze and Google's "one version only" policy. It was a pain in the butt!

I'm glad someone did the work though to get ClassGraph built for Google's infrastructure. It was actually a ton of very difficult work to get module scanning working for JDK 9+, and even asking the JDK team (Alan Bateman etc.) directly, I couldn't get any straight answers about how to use the module API to do this. I finally figured it out. I'm pretty sure that still today, several years later, no other classpath scanner can actually scan modules, only the traditional classpath in JDK 9+, even though I have been trying to promote this solution via StackOverflow etc. -- the solution and its reflection-based implementation are here, for reference:

https://stackoverflow.com/questions/41932635/scanning-classpath-modulepath-in-runtime-in-java-9/45612376#45612376
https://github.com/classgraph/classgraph/blob/latest/src/main/java/nonapi/io/github/classgraph/classpath/ModuleFinder.java

> Right, that's exactly it. I agree it looks like `ModuleClassLoader` is explicitly referencing the enclosing instance, so it will not be affected by this change.

OK, I'll close the bug. Thanks though!

> I'd still recommend avoiding references to `this$` where possible since it's an implementation detail that isn't guaranteed by the spec, but in this specific case I'm not sure what the alternatives would be, since I'm guessing `ModuleClassLoader` doesn't provide a way to get the information you need from its public API.

Right. A good deal of the [`ClassLoaderHandler`](https://github.com/classgraph/classgraph/tree/latest/src/main/java/nonapi/io/github/classgraph/classloaderhandler) code in ClassGraph was contributed by users, including (if I remember right) most of the JBoss code that you referenced. ClassLoaders do change, as does the JDK, so there's an ongoing task to keep updating ClassGraph to handle these changes, and reports like yours are important to keep up this process.

> I checked and it looks like ecj uses the same naming convention. I'm not sure about other source-to-bytecode compilers, though.

Thanks for checking that!
