### ISSUE TITLE
Ignores explicitely set JRE JAR

### ISSUE THREAD

**Issue by parttimenerd** [classgraph/classgraph#578]
Overriding the classpath with a JRE JAR ignores the JAR completely and there seems to be no possibility to turn off this 
behaviour, i.e. the result of

```java
new ClassGraph().verbose().overrideClasspath("/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar")
     .enableClassInfo().scan().getClasspath()
```
is the empty string.

Verbose log is [here](https://github.com/classgraph/classgraph/files/7330428/bla.log).

**Comment by lukehutch** [comment]
Hi, whether a system jar is added with manual override or obtained through automatic discovery, system jars are not scanned by default, for speed. This probably seems counterintuitive if that jar is the only thing in the override classpath, but usually it is only one of multiple jars, and users of ClassGraph almost never need to actually scan system jars.

The solution is to call `.enableSystemJarsAndModules()` before `.scan()`.

Please verify if this works for you. Thanks!

**Comment by parttimenerd** [comment]
This adds all system JARs, not just the one I specifically need.

**Comment by lukehutch** [comment]
This shouldn't add all system jars, as long as you use `.enableSystemJarsAndModules()` in conjunction with `.overrideClasspath()`, since if you call `.overrideClasspath()`, nothing but the override path is supposed to be scanned. 

Here you can see that modules are not scanned if the classpath is overridden:

https://github.com/classgraph/classgraph/blob/latest/src/main/java/nonapi/io/github/classgraph/classpath/ClasspathFinder.java#L124

And here you can see that system jars are only added for scanning if the classpath is not overridden and the classloaders are not overridden:

https://github.com/classgraph/classgraph/blob/latest/src/main/java/nonapi/io/github/classgraph/classpath/ClasspathFinder.java#L213

Did you test this, or was this just your assumption? If you actually tested it, I don't know how this is happening, because it's not supposed to be possible, given the code linked above. In my own testing, I can't replicate this behavior.

Can you please provide your stderr logs after adding `.enableSystemJarsAndModules()`? Thanks.

**Comment by parttimenerd** [comment]
You're right, the combination works. Thanks for your quick response.

**Comment by lukehutch** [comment]
Great, thanks for verifying.
