### ISSUE TITLE
Getting resources matching a glob/wildcard pattern

### ISSUE THREAD

**Issue by jjlin** [classgraph/classgraph#588]
It would be nice if there were a method like `ScanResult#getResourcesMatchingWildcard()` for cases where you just want to match something simple like `someDir/*.json`. Of course, `ScanResult#getResourcesMatchingPattern()` can do the job, but having to write out something like `Pattern.compile("^" + SOME_DIR + "/.+\\.json$")` is quite a bit uglier.

A more general solution could be having a `ScanResult#getResourcesMatchingPredicate()` method and using that in conjunction with `FilenameUtils#wildcardMatch()` from Apache Commons IO, but I assume this wasn't already implemented because it wouldn't be compatible with Java 7.

Am I missing any simple workarounds for this problem? Thanks.

**Comment by lukehutch** [comment]
Hi @jjlin,

This is a good request, and is very simple to add. Please try the git master version, which implements what you suggested:

```
Pattern.compile("^" + glob.replace(".", "\\.").replace("*", ".*") + "$")
```

The new method is `ScanResult#getResourcesMatchingWildcard(String)`.

**Comment by jjlin** [comment]
Thanks for the quick response. It would be nice to have a more complete implementation, though. Maybe something like https://stackoverflow.com/a/17369948, which is public domain?

(The public domain statement is also archived at [Wayback Machine](https://web.archive.org/web/20210508110911/https://stackoverflow.com/questions/1247772/is-there-an-equivalent-of-java-util-regex-for-glob-type-patterns) in case there are future questions about provenance.)

There's also [`FileSystem#getPathMatcher`](https://docs.oracle.com/javase/7/docs/api/java/nio/file/FileSystem.html#getPathMatcher(java.lang.String)), but it only works on a `Path`.

**Comment by lukehutch** [comment]
(Thanks for caring about provenance -- I do always link my sources in my source code for any patterns I borrow -- I wish more people did!)

I don't know that a solution this complex actually would be useful, because you're just replacing one complex pattern matching language that is actually standardized (regexes) with another complex pattern matching language that is not standardized. Once you have to start escaping characters in another nonstandard pattern language, e.g. `"gl\\[-o\\]b"` given in the examples in the StackExchange page you linked, you may as well be using regular expressions.

Regexes are arcane, difficult to learn, and difficult to get right, but they have the benefit of being roughly standard even across different regex libraries, at least for the simple stuff, and there are a range of testing tools that can help you get a regex pattern right.

The huge benefit of filename globs is that they are extremely useful for a wide range of common usecases. Nobody knows how to use anything but the asterisk, but just that one operator solves a dizzying array of problems.

Feel free to offer counterpoints though :-)

**Comment by jjlin** [comment]
I don't think I would agree that regexes are very standardized. The concepts and capabilities are usually pretty similar, but every language and tool seems to have its own flavor with subtle differences in syntax and sometimes semantics. Maybe one of the first things you would run into is there are a lot of variations in whether parens and + need to be escaped.

Anyway, I would agree that people usually only use pretty basic globbing, but I would say the "basics" include `*` and `?` at least, with simple bracket expressions (`[abc]` or `[a-c]`) also being nice to have.

If you want to stick to just `*` though, I'd say it should at least be replaced with `[^/]*`, otherwise it behaves more like a `**`.

**Comment by lukehutch** [comment]
Regexes are standardized within the Java environment. Yes, there are differences in details between environments.

I added `?` to glob matching -- now we have 

```
Pattern.compile("^" + glob.replace(".", "\\.").replace("*", ".*").replace('?', '.') + "$")
```

And actually since I didn't escape square brackets, these will be passed through to the regexp parser. The parser will also handle backslash escaping.

This is sort of a weird hybrid solution, but do you think this works well enough?

**Comment by lukehutch** [comment]
Oh, I forgot to fix the matching of `*` vs. `**` -- I'll do that too.

**Comment by jjlin** [comment]
I don't work for the government, but it's probably good enough anyway. :)

It would be nice to have the docs call out the fact that brackets are passed straight through and will be interpreted accordingly by the regex engine.

Thanks!

**Comment by lukehutch** [comment]
Done, please check the Javadoc in the last commit.

**Comment by lukehutch** [comment]
The latest logic is:

```
Pattern.compile("^"
                + glob.replace(".", "\\.")
                        .replace("*", "[^/]*")
                        .replace("[^/]*[^/]*", ".*")
                        .replace('?', '.')
                + "$")
```

I think this would keep happy 99% of people who don't want to bother with getting regexps right, but who know how to use globs.

**Comment by jjlin** [comment]
Looks good to me. Thanks!

**Comment by lukehutch** [comment]
Released in 4.8.129. Thanks for your suggestion and your responsive feedback!

**Comment by lukehutch** [comment]
Release notes: https://github.com/classgraph/classgraph/releases/tag/classgraph-4.8.129

**Comment by jjlin** [comment]
Nice, thanks. I think the release notes should say "`*` matches **zero** or more characters other than `/`", unless I'm missing something.

**Comment by lukehutch** [comment]
Correct, thanks, fixed.
