### ISSUE TITLE
Super class's private methods not returned when sub class has same named method

### ISSUE THREAD

**Issue by layer26** [classgraph/classgraph#599]
# Summary
During unit testing of my project, I discovered that the private method of the parent class is not returned if the child class has a method with the same name as the private method of the parent class. This is not resolved by calling the `ignoreMethodVisibility` method.

The access modifiers of methods defined in child classes are irrelevant.

I have attached the code and [verbose.log](https://github.com/classgraph/classgraph/files/7559382/verbose.log) file for testing. some contents (kind of directory paths) have been removed. (marked as `[Censored]`)

# Environments
- classgraph:4.8.133
## Java
```
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```

# Reproduce code
This code is test case of junit5.
```java
import io.github.classgraph.ClassGraph;
import io.github.classgraph.MethodInfo;
import io.github.classgraph.ScanResult;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class ClassgraphTest {
	
	@Test
	void methodScanTest() {
		try (final ScanResult result = new ClassGraph()
				.acceptClasses(SubClass.class.getName())
				.ignoreMethodVisibility()
				.enableMethodInfo()
				.verbose()
				.scan())
		{
			int counter = 0;
			for (final MethodInfo methodInfo : result.getAllClasses().get(0).getMethodInfo()) {
				final String name = methodInfo.getName();
				if (name.equals("testMethod1") || name.equals("testMethod2"))
					counter++;
			}
			
			// This assertion will be passed.
			assertEquals(2, counter);
		}
	}
	
	@Test
	void duplicateMethodScanTest() {
		try (final ScanResult result = new ClassGraph()
				.acceptClasses(SubClass.class.getName())
				.ignoreMethodVisibility()
				.enableMethodInfo()
				.verbose()
				.scan())
		{
			int counter = 0;
			for (final MethodInfo methodInfo : result.getAllClasses().get(0).getMethodInfo()) {
				if (methodInfo.getName().equals("duplicateTestMethod"))
					counter++;
			}
			
			// This assertion will be failed.
			assertEquals(2, counter);
		}
	}
	
	public static class SuperClass {
		
		private void testMethod1() {
		
		}
		
		private void duplicateTestMethod() {
		
		}
	}
	
	public static class SubClass extends SuperClass {
		
		public boolean isSubClassCalled = false;
		
		public void testMethod2() {
		
		}
		
		public void duplicateTestMethod() {
		
		}
	}
}
```

**Comment by lukehutch** [comment]
Correct, but this is actually an intentional design decision.

Since you use `.acceptClasses(SubClass.class.getName())`, you are only finding the methods accessible from `SubClass`. If a method in `SubClass` overrides a method in `SuperClass`, then the overridden superclass method is simply not visible or callable directly from the subclass, except via `super.`. Even with regular Java reflection, the declared methods of the superclass can't be accessed without first accessing the superclass.

You can find the `duplicateTestMethod()` method in the superclass by getting the `MethodInfo` of methods in `SuperClass`.

If you want to find all methods, including methods hidden by overriding, then iterate up through the `ClassInfo` hierarchy to each superclass, get the `MethodInfo` objects, and add them to a set. The `hashCode()` and `equals(Object)` methods have been defined to properly remove duplicates:

https://github.com/classgraph/classgraph/blob/latest/src/main/java/io/github/classgraph/MethodInfo.java#L905

I don't know if there would be utility in adding code to ClassGraph to handle this case, since generally when people are looking for `MethodInfo` objects, they are not looking for superclass methods that are not even callable from the referenced class, because they have been overridden. I'm happy to be corrected though, if this is likely to be a common requirement. Why exactly do you need the hidden methods?

**Comment by layer26** [comment]
It's understandable that overridden methods aren't called as a result of a search. However, private methods cannot override. So this issue is private method is not returning if method name duplicated even method is not overridden.

When it is said that the hidden method of the parent class is not scanned regardless of whether the `ignoreMethodVisibility ` method is called, the `methodScanTest` test of the Reproduce code should also fail, but the test actually passes.

I need access to private methods for initialization related tasks, similar to Spring's `@PostConstruct` annotation. I know that Spring does not call PostConstruct in the parent class, but my project requires it, so I am implementing the function.

**Comment by lukehutch** [comment]
@10sa yes, but private methods in a superclass simply cannot be accessed in any way from the sub-class. So your expectation that you should be able to find these superclass methods starting from only a reference to the subclass doesn't reflect what is even possible in the Java world.

As I pointed out, you can still get these methods though, if you really need them. But you have to start searching from the superclass, not from the subclass.

Here's a pattern for you. Please see if this gives you what you need.

```java
Set<MethodInfo> allMethodInfo = new HashSet<>();
for (ClassInfo ci = scanResult.getClassInfo(className); ci.getSuperclass() != null; ci = ci.getSuperclass()) {
    allMethodInfo.addAll(ci.getMethodInfo());
}
```

I don't think this should be the default behavior of the API, however, since the current API mimics how Java method visibility works.

**Comment by layer26** [comment]
I see. Although it was modified differently from the your suggested method, I determined that this was a design issue with my implementation, so i decided to leave it as the responsibility of the child class whether or not to call the `@PostConstruct` method of the parent class to implement the functionality.

Thanks for your answer.

**Comment by lukehutch** [comment]
Well like I said, you can still find and call the `@PostConstruct` annotated method of the superclass, but you have to search for that by sinply getting the methods of the superclass, not the subclass. Hope this helps.
