### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by KojiV** [classgraph/classgraph#710]
Hey, I'm really sorry I'm making a issue just to ask a question, but I wanted to ask: is there any way to reduce the jar size when using classgraph in the compiled jar? In the Minecraft Spigot scene, jar size is valued (at least to me) more than most programs, and it adds almost half a mb, which stupidly enough is pretty big, especially considering I'm adding it to my dev kit which already adds a ~500 kb. Again, I'm really sorry, but I didn't see anywhere else to ask.

**Comment by lukehutch** [comment]
Hey @KojiV, I noticed the large size recently, and I'm actually shocked ClassGraph is that big, because almost the entire size is contained in bytecode. It started out as a tiny project, and it has just grown over the years! I didn't realize JVM classfiles were so inefficient in size.

There is one part of ClassGraph that will be removed in a future version, which is JSON processing, and that will remove a couple of hundred kb, but it won't be that significant a reduction. I'm also going to split the library into two pieces (one as a fast VFS layer), but that won't reduce your total size.

The best suggestion I can give you is that you could try build-time scanning:

https://github.com/classgraph/classgraph/wiki/Build-Time-Scanning

You may also be able to reduce code size by compiling your whole app with GraalVM, since it uses partial evaluation to collapse code down into the smallest possible form -- but I have never tried compiling ClassGraph with Graal, and it's possible it wouldn't work. Let me know if you do get this working though!

**Comment by KojiV** [comment]
So I got it back down, but it was a very "hacky" solution. I took the annotation processor I used and moved it to a separate repo, then made my main project use the annotation processor kinda similar to lombok, so it didn't have to add the classgraph stuff but still did the proper annotation function.

So instead of:
Annotation -> My Library -> My Plugin

I made it do these two
My Library -> My Plugin
Annotation -> My Plugin
