### ISSUE TITLE
Expose a way to get the jar version that a Resource belongs to

### ISSUE THREAD

**Issue by holayan24** [classgraph/classgraph#840]
Basically the title, I wonder if there is a way to obtain the version of the jar for a resource in the classpath, kinda like [VersionFinder](https://github.com/classgraph/classgraph/blob/ad7ec172b59c3012e3296ec78d68f0436f2b8d0e/src/main/java/nonapi/io/github/classgraph/utils/VersionFinder.java#L212) for ClassGraph with the internal apis. I rely on a couple of string hacks to get the version but it'd be nice if this is provided by default in the library.

And BTW you guys are doing a fantastic job with the nifty tool!

**Comment by lukehutch** [comment]
Good job finding that class, and you're welcome to steal it, but no, I never added anything like this, because after I have had to deal with the menagerie of different Java runtime systems out there, getting the correct version number for every usecase would probably become yet another near-impossible task! For example, I'm sure OSGi has their own version number system, probably stored in the manifest file... or maybe for Spring, the version number is stored in one of the nested jars, not in the toplevel jar. Also in many cases, there is probably no version number anywhere in the jarfile. Also there are cases where dependency jars are "shaded" (their packages have been renamed) but the entire contents of the jarfile is just merged in with the entire contents of every other dependency, which causes files in common locations (like license files) to be overwritten multiple times by different dependencies. The Java world is a royal mess.

Thanks for the compliment, but at this point ClassGraph is basically close to 100% stable (the bug report rate has dropped to very close to zero), and I'm unlikely to make further significant changes to it.

**Comment by holayan24** [comment]
> Good job finding that class, and you're welcome to steal it, but no, I never added anything like this, because after I have had to deal with the menagerie of different Java runtime systems out there, getting the correct version number for every usecase would probably become yet another near-impossible task! For example, I'm sure OSGi has their own version number system, probably stored in the manifest file... or maybe for Spring, the version number is stored in one of the nested jars, not in the toplevel jar. Also in many cases, there is probably no version number anywhere in the jarfile. Also there are cases where dependency jars are "shaded" (their packages have been renamed) but the entire contents of the jarfile is just merged in with the entire contents of every other dependency, which causes files in common locations (like license files) to be overwritten multiple times by different dependencies. The Java world is a royal mess.
> 
> Thanks for the compliment, but at this point ClassGraph is basically close to 100% stable (the bug report rate has dropped to very close to zero), and I'm unlikely to make further significant changes to it.

Yeah I kind of figured, it's the wild west in java land when it comes to versioning, thanks for taking the time to comment on this though. For the time being I guess using the jar's file name suffices for my use case.
