### ISSUE TITLE
ClasspathElementZip.getClasspathElementURI() returns incorrect URIs under Windows

### ISSUE THREAD

**Issue by cowwoc** [classgraph/classgraph#888]
Version 4.8.177

[verbose.log](https://github.com/user-attachments/files/17447938/verbose.log)

When I invoke `ClassgraphElementZip.getClasspathElementURI()` on a JAR file on Windows, I get back: `file:/C:/Users/Gili/Documents/licensed-app/server/target/lib/client.browser-1.0-SNAPSHOT.jar!/index.html`

When I pass this URI to Jetty, it normalizes it to `file:///C:/Users/Gili/Documents/licensed-app/server/target/lib/client.browser-1.0-SNAPSHOT.jar!/` and complains `Base Resource should not be an alias`.

Upon further investigation, it looks like `file:/` is not actually a valid URI format. Is there any reason that ClassGraph is returning `file:/` instead of `file:///`? Is this by design? Or is this a bug? Thank you in advance.

**Comment by lukehutch** [comment]
Good find. I didn't know `file:` needed to be followed by two slashes `//` -- this is not the case on Linux (or I think macOS).

It's possible `file:` only needs two or three slashes after it if it is preceded by `jar:`, but I don't know.

To complicate things, it looks like Jetty strips away the `index.html` suffix, which means `...SNAPSHOT.jar!/` should not end in `!/` (that should have been stripped too), and if `!` is not present, then there should be no `jar:` prefix either (you get an invalid URI error if you have `jar:` without `!`, or possibly if there is no actual path after `!`, which may also include the root path `/`).

If you could please test out which of the above conditions are true, I would appreciate it -- I don't have a Windows machine handy.

Also, if something needs fixing, I would appreciate a PR to address this, because I don't have time to spend actively developing ClassGraph anymore. Thanks!

**Comment by cowwoc** [comment]
Sorry, the `index.html` thing is my fault. My original bug description was wrong. 

I am the one stripping off the filename and passing `file:/C:/Users/Gili/Documents/licensed-app/server/target/lib/client.browser-1.0-SNAPSHOT.jar` into Jetty's `ResourceFactory.newJarFileResource()`. It adds the `jar:` in front and normalizes the URL (adding the slashes).

As a side-note, this workaround works for me:

`uri = new URI(uri.getScheme(), "//" + uri.getSchemeSpecificPart(), uri.getFragment());`

Once I add those two slashes Jetty is happy. I will try putting together a PR for you...

**Comment by cowwoc** [comment]
@lukehutch Maaaaan, that was painful. The assumption of `file:/` was baked into multiple places. I also renamed some unit tests because Surefire expects test classes to end with the name `Test`. And finally, I had to update the contents of manifest file inside a JAR file that was referenced by one of the tests.

I tested the SNAPSHOT version locally and it fixes this issue for me. Let me know if you need anything from me to cut a release. Thanks.

**Comment by lukehutch** [comment]
@cowwoc Yeah, ClassGraph is complex... sorry about that!

I'll take a look at your changes, but I'm not sure when I will get to this...

**Comment by lukehutch** [comment]
Sorry, this issue slipped my mind! I pushed out the fix in 4.8.179.

**Comment by cowwoc** [comment]
I just tested the new version. The fix works.
